-- Pins the official rules in Forums → Rules. Generated by scripts/build-pages.mjs from scripts/rules-data.mjs.
-- Only inserts if the post does not exist yet, so edits made in /admin are never overwritten.
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Official Server Rules', 'By joining OVERTHRONE SMP – the Minecraft server, our Discord, the forums or the store – you agree to these rules.

Unless a section says otherwise, every rule applies everywhere OVERTHRONE exists: in-game, in Discord, on the forums and in private messages about the server.

Staff may act on behaviour that breaks the spirit of these rules even if it is not listed. Not knowing the rules is not an excuse.

[Open the full rules page](/rules)

## 1. Global Bans
Breaking these rules can lead to a temporary or permanent ban from every OVERTHRONE platform.

- 1.1 **No cheating.** Hacked clients, X-ray (mods, resource packs or texture tricks), freecam abuse, kill aura, auto-clickers, macros and any client mod that gives an unfair advantage are not allowed.
- 1.2 **No exploiting.** Duplication glitches, unintended mod interactions, bypassing claims and any bug that gives an advantage are banned. Found one? Report it privately to staff – you may be rewarded.
- 1.3 **No ban or mute evasion.** Using another account to get around a punishment extends it to every account you use.
- 1.4 **No account sharing or selling.** You are responsible for everything done on your account.
- 1.5 **No real-money trading.** Selling or buying in-game items, currency, Throne Shards, bases or accounts for real money or anything outside the server is not allowed.
- 1.6 **No threats or attacks.** DDoS threats, doxxing, swatting, hacking attempts and sharing anyone''s personal information result in an immediate permanent ban.
- 1.7 **No lag machines.** Builds, farms or redstone made to lag or crash the server or other players are not allowed.
- 1.8 **No illegal content.** Anything illegal, or links to it, is banned everywhere.

## 2. Chat & Global Mutes
Breaking these rules can lead to a warning, a mute or a ban.

- 2.1 **Respect everyone.** No harassment, bullying, targeted insults or encouraging others to do so.
- 2.2 **No hate speech or discrimination** based on race, religion, gender, sexuality, nationality, disability or anything else.
- 2.3 **No NSFW content.** No sexual, gore or shocking content in chat, names, skins, builds, signs, books or images.
- 2.4 **No spam.** No flooding, repeated messages, excessive caps, character spam or wall-of-text messages.
- 2.5 **No advertising.** Do not promote other servers, IPs, websites, stores, Discord servers or your own social media without staff permission.
- 2.6 **English in public chat** so staff can moderate it. Other languages are fine in private messages.
- 2.7 **No impersonation** of staff, YouTubers or other players.
- 2.8 **No drama-starting.** Keep arguments, politics and controversial topics out of public chat.
- 2.9 **Don''t share personal information** – yours or anyone else''s.

## 3. SMP Gameplay
Rules for playing in the realms of OVERTHRONE SMP.

- 3.1 **No griefing or stealing** from builds, claims or containers that are not yours.
- 3.2 **No spawn-killing or trapping** players at spawn, portals, Gates or respawn points.
- 3.3 **No combat logging.** Leaving the game to escape a fight counts as a loss and may be punished.
- 3.4 **PvP only where it is enabled.** Follow the PvP rules of each realm and event.
- 3.5 **Don''t block shared areas.** Do not block Gates, dungeons, boss arenas, portals, paths or public builds, and don''t camp them to stop others playing.
- 3.6 **Keep builds appropriate.** No offensive, NSFW or political builds, and don''t build right next to someone else without asking.
- 3.7 **Fair trading.** Scamming players in trades, shops, the auction house or deals made through Discord is not allowed.
- 3.8 **No unfair AFK farming.** AFK machines that abuse mods or bypass AFK limits are not allowed.
- 3.9 **Report bugs, don''t abuse them.** Use the Bug Reports forum or a Discord ticket.

## 4. Discord
The Chat & Global Mutes rules also apply in Discord.

- 4.1 **Use the right channels** and stay on topic.
- 4.2 **Don''t ping staff or roles** without a real reason. For help, open a ticket.
- 4.3 **No unsolicited DMs** to members for advertising, trading or scams.
- 4.4 **Keep your profile appropriate** – name, avatar, status and banner.
- 4.5 **Voice chat:** no soundboards, earrape, screaming or recording people without their permission.
- 4.6 **Follow Discord''s Terms of Service** and Community Guidelines.

## 5. Forums
Rules for the OVERTHRONE forums on this website.

- 5.1 **Post in the right category** and use a clear title.
- 5.2 **No spam, bumping or low-effort posts.** Don''t reply just to raise your post count.
- 5.3 **No necroposting** – don''t revive old threads unless you have something useful to add.
- 5.4 **Player Reports** need proof (video or screenshots) and should stay factual. Don''t call players out in public threads.
- 5.5 **Suggestions** should be constructive. Explain the idea and why it helps the server.
- 5.6 **Don''t argue with staff decisions in public.** Use an appeal instead.

## 6. Store & Purchases
Rules for purchases made on the OVERTHRONE store (powered by Tebex).

- 6.1 **All purchases are final.** Digital items are delivered instantly and cannot be refunded unless required by law.
- 6.2 **Chargebacks and payment disputes** lead to a permanent ban on every OVERTHRONE platform.
- 6.3 **Use your exact Minecraft username** at checkout. We can''t move purchases made to the wrong account.
- 6.4 **Ranks and perks do not protect you from the rules.** Banned players do not get refunds.
- 6.5 **Perks may change** as the server develops, to keep gameplay fair and balanced.
- 6.6 **Only buy from the official store.** Purchases from anyone else are real-money trading and are not allowed.

## 7. Punishments & Appeals
How staff handle rule breaks.

- 7.1 **Punishments usually escalate:** warning → mute → temporary ban → permanent ban. Serious rule breaks can skip straight to a permanent ban.
- 7.2 **Staff decisions are final in the moment.** If you think a punishment was unfair, appeal it – don''t argue in chat.
- 7.3 **Appeals** are made through a ticket in our Discord. Be honest and include your username, the punishment and why it should be reviewed.
- 7.4 **Lying to staff** or faking evidence makes a punishment worse.
- 7.5 **These rules can change at any time.** Check this page for the latest version.

Last updated 3 October 2026.', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'rules'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Official Server Rules');
