-- Player Guide posts, missing forum categories and the RPG world realm.
-- Generated by scripts/build-pages.mjs from scripts/guide-data.mjs. Every statement only adds
-- what is missing (or replaces untouched seed text), so edits made in /admin are never overwritten.

INSERT OR IGNORE INTO forum_categories (section, name, slug, description, icon, sort_order) VALUES ('OVERTHRONE Information', 'Player Guides', 'guides', 'How to join, keybinds, combat, claims and the full mod list.', 'compass', 15);

INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Start Here: Joining OVERTHRONE', '## Start Here
OVERTHRONE is a modded Minecraft server (NeoForge 1.21.1, around 100 mods). You need the modpack to join, as a normal Minecraft client can''t connect.

- **1. Get the modpack** Download the OVERTHRONE modpack and import it into your launcher (CurseForge, Prism or the Modrinth app). The download link is posted in our Discord.
- **2. Give Minecraft enough memory** In your launcher, set the memory (RAM) for the pack to **6–8 GB**. Less than that causes lag spikes and crashes with this many mods.
- **3. Join the server** Add a server with the address **overthronesmp.net** and join. The first load takes a while because of the mods. That''s normal.
- **4. Fix your keybinds** Several mods share the same default keys. Spend two minutes on the [keybind fixes](/guide#keybinds) before you fight anything.
- **5. Read the rules** Short version: no cheats, no griefing, be decent. Full list on the [rules page](/rules).
- **6. Link your Discord** In our Discord, run **/link** with your Minecraft name while you''re online in-game. You''ll get a 6-digit code in Minecraft chat. Then run **/verify** with that code in Discord.

## Your First Hour
A quick route through the server so you know where everything is.

- **1. Explore the hub** You spawn in the OVERTHRONE hub, a city above the clouds. The warp boards there list every destination, or type **/warp hub** to come back any time.
- **2. Go to the RPG world** Type **/rpg**. The RPG world is a protected city where nobody can break or place blocks. It holds the Quest Board, the Arcade & Trade Hall and the Arcanum.
- **3. Talk to Questmaster Orin** Right-click Orin in the RPG world to open the quest book. You can also open it with the quest book button in your inventory. Start with the first quests to earn coins and gear.
- **4. Visit the Arcade** Type **/warp arcade** to see the gacha machines, the vending machines and the exchange counter. Everything there is paid for with coins you earn in game.
- **5. Pick a home** Head to the survival world with **/warp survival**, find a spot and claim it with Open Parties and Claims (press **''**, the apostrophe key) so nobody can grief it.

[Open the full Player Guide](/guide#start)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'guides'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Start Here: Joining OVERTHRONE');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Keybinds & Fixing Key Conflicts', '## Keybinds
These are the default keys for the main mods. Change any of them in Options → Controls → Key Binds. If your modpack already came with different keys, use those.

**Epic Fight (combat)**
- **R**: Switch between battle mode and mining mode
- **Left Mouse**: Attack (in battle mode)
- **Right Mouse**: Guard / block
- **Left Alt**: Dodge
- **Space**: Movement skill (for example a double jump), when you have one equipped
- **Left Mouse**: Weapon skill. It shares the attack button by default; many players move it to a mouse side button
- **G**: Lock on to a target
- **← / →**: Switch lock-on target
- **Middle Mouse**: Move the lock-on freely
- **K**: Skill menu (equip and upgrade skills)
- **Y**: Emote wheel

**Iron''s Spells ''n Spellbooks (magic)**
- **R**: Spell wheel: pick a spell from your spellbook
- **V**: Cast the selected spell
- **Left Alt + Scroll**: Scroll through the spell bar
- **Not set**: Quick-cast slots 1–15: bind these if you use a lot of spells

**Maps, waypoints and claims**
- **M**: Xaero''s World Map
- **Y**: Xaero''s Minimap settings
- **B**: Xaero''s: add a waypoint
- **U**: Xaero''s: waypoint list
- **M**: FTB Chunks map (the pack has both map mods)
- **'' (apostrophe)**: Open Parties and Claims menu: claims, parties and settings

**Voice chat, backpacks and other mods**
- **V**: Simple Voice Chat menu (proximity voice)
- **M**: Mute your microphone
- **N**: Turn voice chat off/on
- **H**: Hide voice chat icons
- **G**: Voice chat groups
- **B**: Open your Sophisticated Backpack
- **Alt + Z / Alt + X**: Toggle backpack upgrades 1 and 2
- **R / U**: JEI: recipes / uses of the item under your mouse (in inventories)
- **O**: Iris: choose a shader pack
- **K**: Iris: turn shaders on/off
- **R**: Iris: reload shaders

**Tensura: Reincarnated** and other mods add their own keys for skills and menus. Open Options → Controls → Key Binds and look through the Tensura categories.

## Fix Key Conflicts
With the default keys, one button does several things at once. For example, R switches Epic Fight mode, opens the spell wheel and reloads shaders. Here''s a setup that fixes all of them.

- **R**: change **Iron''s Spells: Spell Wheel** to **Z** (shared by Epic Fight mode switch · Iron''s spell wheel · Iris reload shaders)
- **R**: unbind **Iris: Reload Shaders**
- **V**: change **Iron''s Spells: Cast Spell** to **X or a mouse side button** (shared by Iron''s cast spell · Voice chat menu)
- **K**: unbind **Iris: Toggle Shaders** (use O instead) (shared by Epic Fight skill menu · Iris toggle shaders)
- **M**: unbind **FTB Chunks: Map** (use Xaero''s) (shared by Xaero''s World Map · FTB Chunks map · Voice chat mute)
- **M**: change **Voice Chat: Mute Microphone** to **J**
- **G**: unbind **Voice Chat: Groups** (groups are in the V menu) (shared by Epic Fight lock-on · Voice chat groups)
- **B**: unbind **Xaero''s: New Waypoint** (add waypoints from the map) (shared by Backpack · Xaero''s add waypoint)
- **Y**: unbind **Xaero''s: Minimap Settings** (shared by Epic Fight emotes · Xaero''s minimap settings)

Conflicting keys show in red in Options → Controls → Key Binds. If a button suddenly does two things, check there first.

[Open the full Player Guide](/guide#keybinds)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'guides'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Keybinds & Fixing Key Conflicts');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Combat, Magic & Skills', '## Combat, Magic & Skills
Fighting on OVERTHRONE uses Epic Fight, so it plays very differently from vanilla Minecraft.

- **Battle mode vs mining mode.** Press **R** to swap. Battle mode gives you combos, guarding and dodging with weapons. Mining mode is normal Minecraft for building and digging.
- **Dodge, don''t tank.** **Left Alt** dodges through attacks. Big bosses hit hard, so learn their patterns and dodge their big swings.
- **Guard** with **Right Mouse**. Blocking at the right moment is much better than eating hits.
- **Weapon skills.** Each weapon type has its own skill and combo. Weapons from Weapons of Miracles and Simply Swords have special movesets.
- **Skill menu (K).** Equip skills like dodges and passives, and grow them with the Epic Fight Skill Tree.
- **Magic.** Iron''s Spells ''n Spellbooks adds spellbooks, scrolls and mana. Put spells into your spellbook at an Inscription Table, choose one with the spell wheel and cast it.
- **Tensura: Reincarnated** is the core of the server: your race, unique and extra skills, magic and battlewills. Browse them on the [Tensura Skills](/tensura) page.
- **Classes.** Visit **/warp classes** in the hub to see the classes.

Damage numbers (from Combat Numbers) pop up when you hit something, so you can see which weapon and skills actually do more damage.

[Open the full Player Guide](/guide#combat)', 'OVERTHRONE Staff', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'guides'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Combat, Magic & Skills');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Claims, Parties & Voice Chat', '## Claims, Parties & Voice
Protect your base and play with friends.

- **Claim your land.** Press **''** (apostrophe) to open Open Parties and Claims, then claim chunks on the map. Claimed blocks and containers are protected from other players.
- **Make a party.** Create a party in the same menu and invite your friends so they can build and open chests in your claims.
- **Proximity voice chat.** Simple Voice Chat lets you talk to players near you. Press **V** to open its menu and test your microphone. Set push-to-talk in the controls if you don''t want an open mic.

[Open the full Player Guide](/guide#claims)', 'OVERTHRONE Staff', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'guides'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Claims, Parties & Voice Chat');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Full Mod List', '## Mod List
The main mods that change how you play. The full pack also has libraries and performance mods.

**Core:** Tensura: Reincarnated, Tensura: Kumo Desu, Tensura Leveling, Epic Fight, Epic Fight Extra, Epic Fight Skill Tree, Weapons of Miracles

**Magic & gear:** Iron''s Spells ''n Spellbooks, Simply Swords, Apotheosis, Apothic Enchanting, Apothic Attributes, Artifacts, Sophisticated Backpacks

**Bosses & mobs:** L_Ender''s Cataclysm, Mowzie''s Mobs, Born in Chaos, Deeper and Darker

**Worlds & exploring:** The Aether, Regions Unexplored, ChoiceTheorem''s Overhauled Village, YUNG''s Better Dungeons, Dungeons and Taverns, Explorify, Lootr, Waystones, Nature''s Compass

**Quests & economy:** FTB Quests, Lightman''s Currency, Jobs+

**Friends & claims:** Open Parties and Claims, FTB Teams, FTB Chunks, Simple Voice Chat

**Helpful:** JEI, Jade, Xaero''s Minimap, Xaero''s World Map, Combat Numbers, Better Lock On

**Performance & visuals:** Sodium, Iris Shaders, ImmediatelyFast, ModernFix, FerriteCore, Entity Culling, Dynamic FPS

[Open the full Player Guide](/guide#mods)', 'OVERTHRONE Staff', 0, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'guides'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Full Mod List');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Known Issues & Fixes', '## Known Issues & Fixes
Common problems and how to fix them.

**My armour is invisible in Epic Fight battle mode**
This is a known incompatibility between Epic Fight and some modded armour, including Tensura armour. Your armour still protects you; it just isn''t drawn in battle mode. Press **R** to switch to mining mode to see it again.

**My camera glitches in third person**
This happens when two lock-on systems run together: Epic Fight''s lock-on (**G**) and Better Lock On. Use only one. Unbind the one you don''t want in Options → Controls → Key Binds.

**The game crashes or freezes while loading**
Usually not enough memory. Give the pack **6–8 GB** of RAM in your launcher, then restart. Close other heavy programs.

**My FPS is low**
Turn shaders off with **O** (pick "None"), lower Render Distance to 8–12 and Simulation Distance to 6–8 in Video Settings. Sodium''s extra options are under Video Settings too.

**My keys do two things at once**
Follow the [key conflict fixes](/guide#key-conflicts).

**Nobody can hear me in voice chat**
Press **V**, open the settings and pick the right microphone. Make sure you aren''t muted (**M**) and that voice chat isn''t turned off (**N**).

**I found a bug or exploit**
Report it privately in a Discord ticket. Don''t abuse it; using bugs for an advantage is against [rule 1.2](/rules#global-bans).

[Open the full Player Guide](/guide#fixes)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'help'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Known Issues & Fixes');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'FAQ', '## FAQ
Quick answers.

**Is the server free?**
Yes. You need Minecraft: Java Edition and the OVERTHRONE modpack.

**Can Bedrock or console players join?**
No. Modded servers only work with Java Edition on PC.

**Can I add my own mods?**
Only client-side mods that don''t give an advantage, such as minimaps you already have, shaders or performance mods. X-ray, freecam and other cheat mods get you banned. If you''re not sure, ask in a Discord ticket first.

**What version is it?**
Minecraft 1.21.1 with NeoForge. Use the modpack so every mod version matches the server.

**Where do I get help?**
Open a ticket in the Discord, or check the [forums](/forums).

[Open the full Player Guide](/guide#faq)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'help'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'FAQ');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Coins, the Arcade & Trading', '## Coins & the Arcade
The server runs on Lightman''s Currency coins: real items you carry, spend and trade.

**Coins, lowest to highest:** Copper → Iron → Gold → Emerald → Diamond → Netherite

10 of each coin is worth 1 of the next. So 1 Netherite coin = 100,000 Copper.

- **Earn** (In game only): Quest rewards (especially the Ledger), voting, trading with players and selling what you gather.
- **Spend** (/warp arcade): The Arcade & Trade Hall in the RPG world: gacha machines for weapons, armour, enchants, runes and misc items, vending machines, and the exchange counter.
- **Share** (Community Chest): Leave spare gear for new players, or grab something to get started. Take what you need, not everything.

**Everything in the Arcade is grindable for free.** Coins come from playing. You can''t buy them with real money, and selling coins or items for real money breaks [rule 1.5](/rules#global-bans).

Vote for the server every day on the [Vote page](/vote) for extra rewards.

[Open the full Player Guide](/guide#economy)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'economy'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Coins, the Arcade & Trading');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'How Quests Work', '## Quests
There are over 1,100 quests in the quest book. Open it by talking to Questmaster Orin in the RPG world, or with the quest book button in your inventory.

- **The Quest Board** (100 quests): The Hunter''s path from E-Rank to S-Rank. Every 10th quest is a Rank Trial. Rewards are balance, XP and gear that gets better at each rank.
- **The Hunter''s Ledger** (1,012 quests): Ten Ledgers of coin quests covering farming, exploring, crafting, fishing, the Nether, magic, caves, bounties, the End and legendary feats. Finishing all of them pays about 1,500 Netherite coins.

**Quest Board rank · Quests · Chapter**
- **E-Rank**: 1–20 · The Awakening
- **D-Rank**: 21–40 · The Wilds
- **C-Rank**: 41–60 · Into the Depths
- **B-Rank**: 61–80 · The Hunt Beyond
- **S-Rank**: 81–100 · Overthrow

**Ledger · Theme**
- **I. Homestead**: Farming, food and animals
- **II. Wanderlust**: Exploring biomes and structures
- **III. Artisan''s Guild**: Crafting and building
- **IV. Tides & Tails**: Fishing and the ocean
- **V. Into the Nether**: The Nether and its fortresses
- **VI. Arcane Arts**: Enchanting, brewing and magic
- **VII. The Deep Below**: Caves, mining and the deep dark
- **VIII. Bounty Board**: Hunting mobs
- **IX. The Far End**: The End
- **X. Legends of the Realm**: The hardest feats and bosses

- Each Ledger unlocks once you''ve finished entry 50 of the one before it.
- Every 10th Ledger entry and each finale also gives **enchanted gear**. The strongest modded weapons, armour and spellbooks come from the late Ledgers.
- Hand-in quests take the items from your inventory, so don''t hand in anything you want to keep.

[Open the full Player Guide](/guide#quests)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'quests'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'How Quests Work');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Bosses & Dungeons Guide', '## Bosses & Dungeons
The pack adds a lot of things that want you dead. Gear up, bring food, and don''t fight the big ones alone.

- **L_Ender''s Cataclysm** (Bosses): Huge boss fights in their own structures: Ignis, the Netherite Monstrosity, the Ender Guardian, the Leviathan, the Harbinger, the Ancient Remnant, Maledictus and Scylla.
- **Mowzie''s Mobs** (Bosses): The Ferrous Wroughtnaut, Frostmaw, Umvuthi and the Naga, each with its own attack pattern to learn.
- **The Aether** (Sky dimension): A floating dimension with dungeons and bosses: the Slider, the Valkyrie Queen and the Sun Spirit.
- **Deeper and Darker** (The Otherside): A dimension reached from Ancient Cities in the deep dark, home to the Stalker. Sneak, and be quiet.
- **Born in Chaos** (Night mobs): Nightmarish monsters that make the night much more dangerous. Don''t wander far from a light source.
- **Dungeons & loot** (Explore): YUNG''s Better Dungeons, Dungeons and Taverns and Explorify add structures everywhere. Lootr gives every player their own loot from the same chest.

**Apotheosis** can make any mob an elite with extra powers, and gives gear random affixes and gem sockets. If a mob has a name and glows, be careful.

[Open the full Player Guide](/guide#bosses)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'bosses'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Bosses & Dungeons Guide');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Worlds & Warps', '## Worlds & Warps
Use warps to get around fast. The warp boards in the hub list every destination.

- **/warp hub**: OVERTHRONE hub
- **/warp survival**: Survival world
- **/warp realms**: Realm portals
- **/warp market**: Market
- **/warp tavern**: Tavern
- **/warp classes**: Classes
- **/warp hunters**: Hunters
- **/warp crates**: Crates
- **/warp afk**: AFK area
- **/rpg**: RPG world
- **/warp arcade**: Arcade & Trade Hall
- **/warp arcanum**: The Arcanum: enchanting & runes

- **The RPG world is protected.** You can''t break or place blocks, and buckets, flint and steel, fire charges and explosions are blocked. It''s a city to visit, not to build in.
- **Back to the hub:** walk through the portal in the RPG world to return to the hub.
- **Travel further:** activate Waystones as you find them to teleport between them. Use Nature''s Compass to find a biome.
- **Maps:** Xaero''s Minimap and World Map (**M**) show where you are and your waypoints.

[Open the full Player Guide](/guide#worlds)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'realms'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Worlds & Warps');

INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Introduce Yourself in the Discord', 'Forum posting for players is coming later. For now, say hi in our Discord and tell us your Minecraft name, what you like to play and how you found OVERTHRONE.

[Join the Discord](https://discord.gg/overthronesmp)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'introductions'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Introduce Yourself in the Discord');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Where the Community Talks', 'Most chat happens in our Discord and in-game. Join the Discord to talk with other Hunters, find a party and see what''s new.

[Join the Discord](https://discord.gg/overthronesmp)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'general-discussion'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Where the Community Talks');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Share Your Screenshots & Videos', 'Post your builds, boss kills and clips in the media channels on our Discord. The best ones may be featured on the website and in trailers.

[Join the Discord](https://discord.gg/overthronesmp)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'screenshots-media'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Share Your Screenshots & Videos');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'How to Suggest Something', 'Use the **/suggest** command in our Discord. Every suggestion gets a number and staff mark it as accepted, considered or denied.

- Explain the idea and why it helps the server.
- One idea per suggestion.
- Check the existing suggestions first.

[Join the Discord](https://discord.gg/overthronesmp)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'suggestions'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'How to Suggest Something');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'How to Report a Player', 'Open a **Report a Player** ticket in our Discord. Include:

- Your Minecraft username
- Who you''re reporting
- What happened, with **video or screenshots**

Reports without proof can''t be acted on. Don''t call players out in public chat.

[Join the Discord](https://discord.gg/overthronesmp)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'player-reports'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'How to Report a Player');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'How to Report a Bug', 'Open a **General Support** ticket in our Discord with:

- What you were doing
- What happened, and what you expected to happen
- Screenshots, or your crash report if the game crashed

Exploits (duplication glitches and the like) should be reported privately and never used. See [rule 1.2](/rules#global-bans).

[Join the Discord](https://discord.gg/overthronesmp)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'bug-reports'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'How to Report a Bug');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Parties Now, Guilds Later', 'A full guild system is planned. Until then, team up with a **party** in Open Parties and Claims: press **''** (apostrophe), create a party and invite your friends so you can share claims, chests and builds.

Looking for people to play with? Ask in our Discord.

[Claims, parties & voice chat](/guide#claims)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'guilds'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Parties Now, Guilds Later');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'The Gates: Under Development', 'The Gate and dungeon system is still being built. Gate details will be posted here and in **Announcements** when it''s ready.

Until then, plenty of dungeons are already out there: Cataclysm and Mowzie''s Mobs boss arenas, YUNG''s Better Dungeons and Dungeons and Taverns.

[Bosses & dungeons](/guide#bosses)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'gates'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'The Gates: Under Development');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Tensura: Reincarnated on OVERTHRONE', '**Tensura: Reincarnated** is the core mod of the server: your race, unique and extra skills, magic and battlewills.

- Browse skills, magics and battlewills on the [Tensura Skills](/tensura) page as we add them.
- Tensura has its own keys for skills and menus. Find them in Options → Controls → Key Binds under the Tensura categories.
- If your Tensura armour turns invisible in Epic Fight battle mode, that''s a known incompatibility. It still protects you. Press **R** for mining mode to see it.

[Combat, magic & skills](/guide#combat)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'tensura-skills'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Tensura: Reincarnated on OVERTHRONE');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Rank Trials on the Quest Board', 'The full Hunter rank requirements are still being finalised. Until then, the Quest Board is your path: it runs from **E-Rank to S-Rank**, and every 10th quest is a **Rank Trial**.

- E-Rank: The Awakening (quests 1–20)
- D-Rank: The Wilds (21–40)
- C-Rank: Into the Depths (41–60)
- B-Rank: The Hunt Beyond (61–80)
- S-Rank: Overthrow (81–100)

[How quests work](/guide#quests)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'hunter-progression'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Rank Trials on the Quest Board');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Official Trailer & the New Player Guide', 'The official OVERTHRONE SMP trailer is out! Watch it on the [home page](/#trailer): sky cities, Epic Fight combat, bosses and the RPG world.

We''ve also added a full **[Player Guide](/guide)**: installing the modpack, every important keybind (and how to fix the keys that clash), quests, coins, warps, bosses and fixes for common problems.', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'announcements'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Official Trailer & the New Player Guide');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Update: The Hunter''s Ledger, the Arcade & the RPG World', 'A big content update for OVERTHRONE.

## The Hunter''s Ledger
- **1,012 new quests** across ten Ledgers, from Homestead to Legends of the Realm.
- Rewards are Lightman''s Currency coins, about **1,500 Netherite** for finishing everything, plus enchanted gear every 10th entry.
- The strongest modded weapons, armour and spellbooks are saved for the late Ledgers.

## The RPG World
- A protected city: blocks can''t be broken or placed, and explosions don''t damage it.
- **Questmaster Orin** opens the quest book.
- **The Arcade & Trade Hall** (/warp arcade): gacha machines for weapons, armour, enchants, runes and misc, vending machines, the exchange counter and the Community Chest.
- **The Arcanum** (/warp arcanum): enchanting and runes.

[How quests work](/guide#quests) · [Coins & the Arcade](/guide#economy)', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'server-updates'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Update: The Hunter''s Ledger, the Arcade & the RPG World');
INSERT INTO forum_posts (category_id, title, body, author_name, pinned, published, published_at)
SELECT id, 'Changelog: October 2026', '## Gameplay
- Added the Hunter''s Ledger: 1,012 coin quests in ten chapters, alongside the 100-quest Quest Board.
- Added the RPG world: Quest Board, Arcade & Trade Hall, the Arcanum and the Community Chest.
- The RPG world is now build-protected and has a world border.
- Added Questmaster Orin, who opens the quest book.

## Website
- New [Player Guide](/guide) with verified keybinds and key conflict fixes.
- Official trailer on the home page.
- New guide posts across the forums, and the RPG world added to the Realms.', 'OVERTHRONE Staff', 1, 1, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
FROM forum_categories
WHERE slug = 'changelog'
  AND NOT EXISTS (SELECT 1 FROM forum_posts WHERE title = 'Changelog: October 2026');

INSERT OR IGNORE INTO realms (name, slug, subtitle, description, status, sort_order) VALUES
  ('THE RPG WORLD', 'rpg-world', 'Quests & Trade', 'A protected city of quests, trade and magic: Questmaster Orin and the Quest Board, the Arcade & Trade Hall and the Arcanum.', '', 15);
UPDATE site_settings SET value = 'Seven realms, each with its own role.' WHERE key = 'realms_intro' AND value = 'Six realms, each with its own role.';

UPDATE home_sections SET body = 'OVERTHRONE SMP is a modded dark-fantasy MMORPG server: Tensura: Reincarnated, Epic Fight combat, over 1,100 quests, bosses and a coin economy you grind for in game.

New here? The [Player Guide](/guide) walks you through installing the modpack, the keybinds and your first hour.', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE title = 'Getting Started' AND instr(body, 'is currently under development.') > 0;
