"""The Hunter's Ledger: 10 chapters of quests that reward Lightman's Currency coins.

Each row: (kind, target, count, title)
  have  - have the item in your inventory          give  - hand the items in (taken)
  craft - craft it yourself                        kill  - slay N of a mob
  biome - visit a biome                            struct- find a structure
  stat  - reach a vanilla statistic (custom stats)  xp    - spend N levels
  adv   - earn a vanilla advancement               dim   - enter a dimension
  pot   - have a specific potion (item, potion id) book  - have an enchanted book (enchant id, level)
None of these repeat a task from the original 100 rank quests.
"""

CHAPTERS = []

def chapter(name, color, icon, intro, rows):
    CHAPTERS.append(dict(name=name, color=color, icon=icon, intro=intro, rows=rows))

# ------------------------------------------------------------------ I. HOMESTEAD
chapter("Ledger I: Homestead", "&a", "minecraft:wheat", "Every legend starts with a full belly and a roof overhead.", [
    ("craft", "minecraft:crafting_table", 1, "A Place to Work"),
    ("craft", "minecraft:wooden_hoe", 1, "Tiller of Soil"),
    ("have", "minecraft:wheat_seeds", 32, "Seed Bag"),
    ("adv", "minecraft:husbandry/plant_seed", 1, "A Seedy Place"),
    ("give", "minecraft:carrot", 16, "Carrot Patch"),
    ("give", "minecraft:potato", 16, "Spud Season"),
    ("give", "minecraft:beetroot", 16, "Red Roots"),
    ("craft", "minecraft:furnace", 2, "The Hearth"),
    ("give", "minecraft:baked_potato", 16, "Hot Potatoes"),
    ("craft", "minecraft:bread", 16, "Daily Bread"),
    ("give", "minecraft:apple", 8, "An Apple a Day"),
    ("give", "minecraft:egg", 16, "Egg Hunt"),
    ("give", "minecraft:feather", 32, "Feather Pillows"),
    ("have", "minecraft:milk_bucket", 1, "Fresh Milk"),
    ("craft", "minecraft:bucket", 3, "Bucket Brigade"),
    ("have", "minecraft:water_bucket", 1, "Well Water"),
    ("craft", "minecraft:shears", 1, "Shepherd's Shears"),
    ("give", "minecraft:white_wool", 32, "Shearing Day"),
    ("craft", "minecraft:red_bed", 1, "Sweet Dreams"),
    ("stat", "minecraft:sleep_in_bed", 5, "Well Rested"),
    ("craft", "minecraft:lead", 4, "On a Leash"),
    ("adv", "minecraft:husbandry/breed_an_animal", 1, "The Parrots and the Bats"),
    ("stat", "minecraft:animals_bred", 10, "Matchmaker"),
    ("give", "minecraft:cooked_chicken", 16, "Roast Chicken"),
    ("give", "minecraft:cooked_porkchop", 16, "Pork Roast"),
    ("give", "minecraft:cooked_mutton", 16, "Mutton Supper"),
    ("give", "minecraft:cooked_rabbit", 8, "Hunter's Rabbit"),
    ("give", "minecraft:rabbit_hide", 8, "Soft Hides"),
    ("give", "minecraft:melon_slice", 32, "Melon Mornings"),
    ("give", "minecraft:melon", 8, "Whole Melons"),
    ("give", "minecraft:pumpkin", 8, "Pumpkin Patch"),
    ("have", "minecraft:carved_pumpkin", 4, "Spooky Faces"),
    ("craft", "minecraft:jack_o_lantern", 8, "Lantern Faces"),
    ("craft", "minecraft:pumpkin_pie", 8, "Harvest Pie"),
    ("give", "minecraft:sugar_cane", 32, "Sweet Stalks"),
    ("craft", "minecraft:sugar", 32, "Sugar Rush"),
    ("give", "minecraft:cocoa_beans", 16, "Jungle Beans"),
    ("craft", "minecraft:cookie", 32, "Cookie Jar"),
    ("craft", "minecraft:cake", 1, "Celebration Cake"),
    ("stat", "minecraft:eat_cake_slice", 7, "Slice of Life"),
    ("give", "minecraft:sweet_berries", 32, "Berry Picker"),
    ("give", "minecraft:glow_berries", 16, "Cave Candy"),
    ("give", "minecraft:bamboo", 64, "Panda's Pantry"),
    ("give", "minecraft:cactus", 16, "Prickly Business"),
    ("give", "minecraft:brown_mushroom", 16, "Brown Caps"),
    ("give", "minecraft:red_mushroom", 16, "Red Caps"),
    ("craft", "minecraft:mushroom_stew", 4, "Forager's Stew"),
    ("craft", "minecraft:beetroot_soup", 4, "Beet Soup"),
    ("craft", "minecraft:rabbit_stew", 2, "Rabbit Stew"),
    ("craft", "minecraft:suspicious_stew", 1, "Mystery Stew"),
    ("craft", "minecraft:smoker", 1, "Smokehouse"),
    ("stat", "minecraft:interact_with_smoker", 10, "Smoked Goods"),
    ("craft", "minecraft:campfire", 1, "Campfire Stories"),
    ("stat", "minecraft:interact_with_campfire", 5, "Campfire Cook"),
    ("give", "minecraft:dried_kelp", 32, "Seaside Snacks"),
    ("craft", "minecraft:dried_kelp_block", 4, "Kelp Bales"),
    ("craft", "minecraft:hay_block", 16, "Haystacks"),
    ("craft", "minecraft:composter", 1, "Nothing Wasted"),
    ("give", "minecraft:bone_meal", 32, "Green Thumb"),
    ("craft", "minecraft:beehive", 1, "Bee Keeper"),
    ("adv", "minecraft:husbandry/safely_harvest_honey", 1, "Bee Our Guest"),
    ("give", "minecraft:honey_bottle", 4, "Liquid Gold"),
    ("give", "minecraft:honeycomb", 8, "Waxworks"),
    ("craft", "minecraft:candle", 8, "Candlelight"),
    ("craft", "minecraft:lantern", 8, "Warm Glow"),
    ("craft", "minecraft:flower_pot", 4, "Window Boxes"),
    ("stat", "minecraft:pot_flower", 5, "Potted Garden"),
    ("give", "minecraft:poppy", 16, "Poppy Field"),
    ("give", "minecraft:dandelion", 16, "Dandelion Wishes"),
    ("give", "minecraft:cornflower", 8, "Cornflower Blue"),
    ("give", "minecraft:oxeye_daisy", 8, "Daisy Chain"),
    ("give", "minecraft:azure_bluet", 8, "Bluets"),
    ("give", "minecraft:allium", 4, "Allium Bouquet"),
    ("give", "minecraft:lily_of_the_valley", 4, "Lily of the Valley"),
    ("give", "minecraft:sunflower", 4, "Sunflowers"),
    ("give", "minecraft:lilac", 4, "Lilac Hedge"),
    ("give", "minecraft:rose_bush", 4, "Rose Garden"),
    ("give", "minecraft:oak_sapling", 8, "Oak Grove"),
    ("give", "minecraft:birch_sapling", 8, "Birch Grove"),
    ("give", "minecraft:spruce_sapling", 8, "Spruce Grove"),
    ("give", "minecraft:jungle_sapling", 4, "Jungle Seedlings"),
    ("give", "minecraft:acacia_sapling", 4, "Savanna Seedlings"),
    ("give", "minecraft:dark_oak_sapling", 4, "Dark Oak Seedlings"),
    ("give", "minecraft:cherry_sapling", 4, "Blossom Seedlings"),
    ("give", "minecraft:mangrove_propagule", 4, "Mangrove Roots"),
    ("craft", "minecraft:oak_fence", 32, "Fence Line"),
    ("craft", "minecraft:oak_fence_gate", 4, "Gatehouse"),
    ("craft", "minecraft:oak_door", 2, "Front Door"),
    ("craft", "minecraft:chest", 8, "Pantry Shelves"),
    ("craft", "minecraft:barrel", 4, "Root Cellar"),
    ("craft", "minecraft:bookshelf", 4, "Home Library"),
    ("craft", "minecraft:painting", 4, "Home Gallery"),
    ("craft", "minecraft:item_frame", 8, "Trophy Frames"),
    ("craft", "minecraft:armor_stand", 2, "Display Stand"),
    ("craft", "minecraft:loom", 1, "The Weaver"),
    ("craft", "minecraft:white_banner", 2, "Family Banner"),
    ("craft", "minecraft:red_carpet", 16, "Rolled Rugs"),
    ("craft", "minecraft:packed_mud", 16, "Mud and Straw"),
    ("craft", "minecraft:mud_bricks", 32, "Mud Brick Cottage"),
    ("craft", "minecraft:cauldron", 1, "Kitchen Cauldron"),
    ("stat", "minecraft:fill_cauldron", 5, "Bath Day"),
    ("craft", "minecraft:writable_book", 1, "Farm Journal"),
    ("stat", "minecraft:animals_bred", 40, "Full Barn"),
    ("xp", "", 10, "Farmhand's Wisdom"),
])

# ------------------------------------------------------------------ II. WANDERLUST
chapter("Ledger II: Wanderlust", "&e", "minecraft:compass", "The world is wide. The Ledger pays those who see it.", [
    ("craft", "minecraft:compass", 1, "True North"),
    ("craft", "minecraft:map", 1, "Blank Map"),
    ("stat", "minecraft:walk_one_cm", 100000, "First Kilometre"),
    ("biome", "minecraft:plains", 1, "Open Fields"),
    ("biome", "minecraft:forest", 1, "Into the Woods"),
    ("biome", "minecraft:birch_forest", 1, "White Bark"),
    ("biome", "minecraft:river", 1, "Down by the River"),
    ("biome", "minecraft:beach", 1, "Sandy Toes"),
    ("biome", "minecraft:taiga", 1, "Pine Country"),
    ("biome", "minecraft:swamp", 1, "Bog Trotter"),
    ("stat", "minecraft:jump", 500, "Spring in Your Step"),
    ("biome", "minecraft:desert", 1, "Sea of Sand"),
    ("give", "minecraft:sand", 64, "Hourglass Sand"),
    ("give", "minecraft:sandstone", 32, "Desert Stone"),
    ("biome", "minecraft:savanna", 1, "Acacia Horizon"),
    ("give", "minecraft:acacia_log", 32, "Flat-Top Timber"),
    ("biome", "minecraft:jungle", 1, "Welcome to the Jungle"),
    ("give", "minecraft:jungle_log", 32, "Vine-Wrapped Logs"),
    ("biome", "minecraft:bamboo_jungle", 1, "Bamboo Thicket"),
    ("biome", "minecraft:dark_forest", 1, "Under the Canopy"),
    ("give", "minecraft:dark_oak_log", 32, "Dark Timber"),
    ("struct", "minecraft:village_plains", 1, "Plains Village"),
    ("stat", "minecraft:talked_to_villager", 10, "Small Talk"),
    ("stat", "minecraft:traded_with_villager", 10, "Market Day"),
    ("adv", "minecraft:adventure/trade", 1, "What a Deal!"),
    ("struct", "minecraft:village_desert", 1, "Desert Village"),
    ("struct", "minecraft:village_savanna", 1, "Savanna Village"),
    ("struct", "minecraft:village_taiga", 1, "Taiga Village"),
    ("struct", "minecraft:village_snowy", 1, "Snowy Village"),
    ("biome", "minecraft:snowy_plains", 1, "Whiteout"),
    ("give", "minecraft:snowball", 32, "Snowball Fight"),
    ("give", "minecraft:ice", 32, "Ice Harvest"),
    ("biome", "minecraft:ice_spikes", 1, "Frozen Spires"),
    ("give", "minecraft:packed_ice", 16, "Packed Ice"),
    ("biome", "minecraft:snowy_taiga", 1, "Winter Pines"),
    ("biome", "minecraft:frozen_river", 1, "Frozen River"),
    ("adv", "minecraft:adventure/walk_on_powder_snow_with_leather_boots", 1, "Light as a Rabbit"),
    ("biome", "minecraft:meadow", 1, "Mountain Meadow"),
    ("biome", "minecraft:cherry_grove", 1, "Blossom Season"),
    ("give", "minecraft:cherry_log", 32, "Pink Timber"),
    ("biome", "minecraft:grove", 1, "Snowy Grove"),
    ("biome", "minecraft:snowy_slopes", 1, "Snowy Slopes"),
    ("biome", "minecraft:stony_peaks", 1, "Stony Peaks"),
    ("give", "minecraft:calcite", 16, "Calcite Cliffs"),
    ("biome", "minecraft:jagged_peaks", 1, "Jagged Peaks"),
    ("biome", "minecraft:frozen_peaks", 1, "Frozen Peaks"),
    ("stat", "minecraft:climb_one_cm", 5000, "Ladder Climber"),
    ("adv", "minecraft:adventure/fall_from_world_height", 1, "Caves & Cliffs"),
    ("biome", "minecraft:windswept_hills", 1, "Windswept Hills"),
    ("biome", "minecraft:windswept_forest", 1, "Windswept Forest"),
    ("biome", "minecraft:windswept_gravelly_hills", 1, "Gravel Hills"),
    ("biome", "minecraft:old_growth_spruce_taiga", 1, "Ancient Spruce"),
    ("biome", "minecraft:old_growth_pine_taiga", 1, "Ancient Pines"),
    ("biome", "minecraft:old_growth_birch_forest", 1, "Tall Birches"),
    ("biome", "minecraft:flower_forest", 1, "Flower Forest"),
    ("biome", "minecraft:sunflower_plains", 1, "Sunflower Plains"),
    ("biome", "minecraft:mangrove_swamp", 1, "Mangrove Maze"),
    ("give", "minecraft:mangrove_log", 32, "Mangrove Timber"),
    ("give", "minecraft:mud", 32, "Knee-Deep Mud"),
    ("biome", "minecraft:sparse_jungle", 1, "Jungle's Edge"),
    ("biome", "minecraft:savanna_plateau", 1, "Savanna Plateau"),
    ("biome", "minecraft:windswept_savanna", 1, "Shattered Savanna"),
    ("biome", "minecraft:badlands", 1, "The Badlands"),
    ("give", "minecraft:red_sand", 64, "Red Sands"),
    ("give", "minecraft:terracotta", 32, "Clay Canyons"),
    ("biome", "minecraft:eroded_badlands", 1, "Eroded Spires"),
    ("biome", "minecraft:wooded_badlands", 1, "Wooded Badlands"),
    ("struct", "minecraft:mineshaft_mesa", 1, "Mesa Mineshaft"),
    ("biome", "minecraft:stony_shore", 1, "Stony Shore"),
    ("biome", "minecraft:snowy_beach", 1, "Snowy Beach"),
    ("biome", "minecraft:mushroom_fields", 1, "Mushroom Island"),
    ("give", "minecraft:mycelium", 8, "Mycelium Mat"),
    ("struct", "minecraft:desert_pyramid", 1, "Desert Temple"),
    ("struct", "minecraft:jungle_pyramid", 1, "Jungle Temple"),
    ("struct", "minecraft:swamp_hut", 1, "Witch's Hut"),
    ("struct", "minecraft:igloo", 1, "Igloo"),
    ("struct", "minecraft:pillager_outpost", 1, "Outpost Spotted"),
    ("struct", "minecraft:ruined_portal", 1, "Ruined Portal"),
    ("struct", "minecraft:trail_ruins", 1, "Trail Ruins"),
    ("craft", "minecraft:spyglass", 1, "Spyglass"),
    ("adv", "minecraft:adventure/spyglass_at_parrot", 1, "Is It a Bird?"),
    ("craft", "minecraft:clock", 1, "Pocket Clock"),
    ("have", "minecraft:filled_map", 3, "Mapmaker"),
    ("craft", "minecraft:cartography_table", 1, "Cartographer's Desk"),
    ("stat", "minecraft:interact_with_cartography_table", 5, "Charting the Land"),
    ("stat", "minecraft:sprint_one_cm", 200000, "Marathon"),
    ("stat", "minecraft:minecart_one_cm", 20000, "Rail Rider"),
    ("stat", "minecraft:crouch_one_cm", 5000, "Sneaky Steps"),
    ("stat", "minecraft:jump", 2000, "Parkour"),
    ("stat", "minecraft:traded_with_villager", 50, "Trade Baron"),
    ("stat", "minecraft:talked_to_villager", 50, "Town Gossip"),
    ("struct", "minecraft:mansion", 1, "Woodland Mansion"),
    ("give", "minecraft:spruce_log", 64, "Spruce Stockpile"),
    ("give", "minecraft:birch_log", 64, "Birch Stockpile"),
    ("give", "minecraft:oak_log", 64, "Oak Stockpile"),
    ("stat", "minecraft:walk_one_cm", 500000, "Five Kilometres"),
    ("stat", "minecraft:walk_one_cm", 1000000, "Ten Kilometres"),
    ("stat", "minecraft:walk_on_water_one_cm", 5000, "Water Strider"),
    ("biome", "minecraft:ocean", 1, "Open Ocean"),
    ("biome", "minecraft:deep_ocean", 1, "The Deep Blue"),
    ("biome", "minecraft:warm_ocean", 1, "Coral Waters"),
    ("biome", "minecraft:frozen_ocean", 1, "Arctic Sea"),
    ("stat", "minecraft:sprint_one_cm", 1000000, "Ultra Marathon"),
    ("xp", "", 15, "Traveller's Tales"),
])

# ------------------------------------------------------------------ III. ARTISAN'S GUILD
chapter("Ledger III: Artisan's Guild", "&6", "minecraft:smithing_table", "Builders, tinkerers and redstone wizards are paid in full.", [
    ("craft", "minecraft:stonecutter", 1, "The Stonecutter"),
    ("stat", "minecraft:interact_with_stonecutter", 20, "Precision Cuts"),
    ("craft", "minecraft:polished_andesite", 64, "Polished Andesite"),
    ("craft", "minecraft:polished_diorite", 64, "Polished Diorite"),
    ("craft", "minecraft:polished_granite", 64, "Polished Granite"),
    ("craft", "minecraft:mossy_stone_bricks", 32, "Mossy Masonry"),
    ("craft", "minecraft:chiseled_stone_bricks", 16, "Chiselled Stone"),
    ("have", "minecraft:cracked_stone_bricks", 16, "Weathered Walls"),
    ("have", "minecraft:smooth_stone", 32, "Smooth Stone"),
    ("craft", "minecraft:bricks", 64, "Red Bricks"),
    ("craft", "minecraft:cut_sandstone", 32, "Cut Sandstone"),
    ("craft", "minecraft:red_sandstone", 32, "Red Sandstone"),
    ("have", "minecraft:smooth_sandstone", 32, "Smooth Sandstone"),
    ("craft", "minecraft:deepslate_bricks", 64, "Deepslate Bricks"),
    ("craft", "minecraft:deepslate_tiles", 64, "Deepslate Tiles"),
    ("craft", "minecraft:polished_deepslate", 64, "Polished Deepslate"),
    ("craft", "minecraft:chiseled_deepslate", 8, "Chiselled Deepslate"),
    ("craft", "minecraft:tuff_bricks", 32, "Tuff Bricks"),
    ("craft", "minecraft:polished_tuff", 32, "Polished Tuff"),
    ("craft", "minecraft:chiseled_tuff", 8, "Chiselled Tuff"),
    ("have", "minecraft:glass", 64, "Glassblower"),
    ("craft", "minecraft:glass_pane", 32, "Window Panes"),
    ("craft", "minecraft:purple_stained_glass", 16, "Royal Glass"),
    ("craft", "minecraft:cyan_stained_glass", 16, "Ocean Glass"),
    ("craft", "minecraft:tinted_glass", 4, "Tinted Glass"),
    ("have", "minecraft:white_glazed_terracotta", 8, "Glazed Tiles"),
    ("craft", "minecraft:white_concrete_powder", 32, "Concrete Mix"),
    ("have", "minecraft:white_concrete", 32, "Set in Stone"),
    ("craft", "minecraft:copper_block", 4, "Copper Plating"),
    ("craft", "minecraft:cut_copper", 16, "Cut Copper"),
    ("craft", "minecraft:chiseled_copper", 8, "Chiselled Copper"),
    ("craft", "minecraft:copper_grate", 8, "Copper Grates"),
    ("craft", "minecraft:copper_door", 2, "Copper Door"),
    ("craft", "minecraft:copper_trapdoor", 4, "Copper Hatch"),
    ("craft", "minecraft:copper_bulb", 4, "Copper Bulbs"),
    ("adv", "minecraft:adventure/lighten_up", 1, "Lighten Up"),
    ("adv", "minecraft:husbandry/wax_on", 1, "Wax On"),
    ("adv", "minecraft:husbandry/wax_off", 1, "Wax Off"),
    ("craft", "minecraft:lightning_rod", 4, "Lightning Rods"),
    ("craft", "minecraft:redstone_torch", 8, "Redstone Torches"),
    ("craft", "minecraft:lever", 4, "Pull the Lever"),
    ("craft", "minecraft:stone_button", 4, "Push the Button"),
    ("craft", "minecraft:oak_pressure_plate", 4, "Pressure Plates"),
    ("craft", "minecraft:repeater", 4, "Repeaters"),
    ("craft", "minecraft:comparator", 2, "Comparators"),
    ("craft", "minecraft:redstone_lamp", 4, "Redstone Lamps"),
    ("craft", "minecraft:daylight_detector", 1, "Sunrise Sensor"),
    ("craft", "minecraft:target", 1, "Bullseye Block"),
    ("craft", "minecraft:tripwire_hook", 2, "Tripwire"),
    ("craft", "minecraft:trapped_chest", 2, "Booby Trap"),
    ("craft", "minecraft:piston", 4, "Pistons"),
    ("craft", "minecraft:sticky_piston", 2, "Sticky Pistons"),
    ("craft", "minecraft:observer", 2, "Observers"),
    ("craft", "minecraft:dispenser", 2, "Dispensers"),
    ("craft", "minecraft:dropper", 2, "Droppers"),
    ("craft", "minecraft:hopper", 2, "Hoppers"),
    ("craft", "minecraft:crafter", 1, "The Crafter"),
    ("adv", "minecraft:adventure/crafters_crafting_crafters", 1, "Crafters Crafting Crafters"),
    ("craft", "minecraft:note_block", 4, "Note Blocks"),
    ("stat", "minecraft:tune_noteblock", 10, "Tuning Up"),
    ("stat", "minecraft:play_noteblock", 30, "Concert Night"),
    ("craft", "minecraft:jukebox", 1, "Jukebox"),
    ("craft", "minecraft:rail", 32, "Laying Track"),
    ("craft", "minecraft:powered_rail", 8, "Powered Rails"),
    ("craft", "minecraft:detector_rail", 4, "Detector Rails"),
    ("craft", "minecraft:activator_rail", 4, "Activator Rails"),
    ("craft", "minecraft:minecart", 1, "Minecart"),
    ("craft", "minecraft:chest_minecart", 1, "Cargo Cart"),
    ("craft", "minecraft:hopper_minecart", 1, "Hopper Cart"),
    ("craft", "minecraft:tnt", 2, "Handle With Care"),
    ("craft", "minecraft:tnt_minecart", 1, "Explosive Delivery"),
    ("craft", "minecraft:grindstone", 1, "Grindstone"),
    ("stat", "minecraft:interact_with_grindstone", 5, "Clean Slate"),
    ("craft", "minecraft:smithing_table", 1, "Smithing Table"),
    ("craft", "minecraft:fletching_table", 1, "Fletcher's Bench"),
    ("craft", "minecraft:blast_furnace", 1, "Blast Furnace"),
    ("stat", "minecraft:interact_with_blast_furnace", 10, "Ore Smelter"),
    ("craft", "minecraft:anvil", 1, "The Anvil"),
    ("stat", "minecraft:interact_with_anvil", 5, "Name It"),
    ("craft", "minecraft:lectern", 1, "Lectern"),
    ("craft", "minecraft:chain", 16, "Chains"),
    ("craft", "minecraft:iron_bars", 32, "Iron Bars"),
    ("craft", "minecraft:iron_door", 2, "Iron Door"),
    ("craft", "minecraft:iron_trapdoor", 4, "Iron Hatch"),
    ("craft", "minecraft:ladder", 32, "Ladders"),
    ("craft", "minecraft:scaffolding", 32, "Scaffolding"),
    ("craft", "minecraft:oak_sign", 6, "Signposts"),
    ("craft", "minecraft:oak_hanging_sign", 6, "Hanging Signs"),
    ("craft", "minecraft:glow_item_frame", 4, "Glowing Frames"),
    ("craft", "minecraft:stone_brick_stairs", 32, "Grand Staircase"),
    ("craft", "minecraft:stone_brick_slab", 32, "Stone Slabs"),
    ("craft", "minecraft:stone_brick_wall", 32, "Castle Walls"),
    ("craft", "minecraft:cherry_planks", 64, "Blossom Planks"),
    ("craft", "minecraft:bamboo_mosaic", 32, "Bamboo Mosaic"),
    ("craft", "minecraft:bamboo_planks", 64, "Bamboo Planks"),
    ("craft", "minecraft:chiseled_bookshelf", 2, "Chiselled Bookshelf"),
    ("craft", "minecraft:decorated_pot", 2, "Clay Pots"),
    ("craft", "minecraft:brush", 1, "Archaeologist's Brush"),
    ("craft", "minecraft:magenta_banner", 4, "Guild Banners"),
    ("craft", "minecraft:sea_lantern", 4, "Sea Lanterns"),
    ("craft", "minecraft:end_rod", 4, "Light Rods"),
    ("adv", "minecraft:adventure/lightning_rod_with_villager_no_fire", 1, "Surge Protector"),
    ("adv", "minecraft:adventure/play_jukebox_in_meadows", 1, "Sound of Music"),
    ("xp", "", 20, "Master Craftsman"),
])

# ------------------------------------------------------------------ IV. TIDES & TAILS
chapter("Ledger IV: Tides & Tails", "&b", "minecraft:fishing_rod", "Anglers, tamers and riders: the sea and the wild pay well.", [
    ("craft", "minecraft:fishing_rod", 1, "Gone Fishing"),
    ("stat", "minecraft:fish_caught", 10, "First Catch"),
    ("give", "minecraft:cod", 32, "Cod Run"),
    ("give", "minecraft:salmon", 32, "Salmon Run"),
    ("give", "minecraft:tropical_fish", 8, "Tropical Catch"),
    ("give", "minecraft:pufferfish", 8, "Puffed Up"),
    ("adv", "minecraft:husbandry/fishy_business", 1, "Fishy Business"),
    ("stat", "minecraft:fish_caught", 25, "Weekend Angler"),
    ("give", "minecraft:nautilus_shell", 2, "Shell Collector"),
    ("give", "minecraft:ink_sac", 32, "Ink Well"),
    ("give", "minecraft:glow_ink_sac", 8, "Glowing Ink"),
    ("adv", "minecraft:husbandry/make_a_sign_glow", 1, "Glow and Behold!"),
    ("craft", "minecraft:oak_boat", 1, "Set Sail"),
    ("stat", "minecraft:boat_one_cm", 100000, "Sea Voyage"),
    ("craft", "minecraft:oak_chest_boat", 1, "Cargo Boat"),
    ("craft", "minecraft:bamboo_raft", 1, "Bamboo Raft"),
    ("give", "minecraft:kelp", 64, "Kelp Forest"),
    ("give", "minecraft:seagrass", 32, "Seagrass Meadow"),
    ("give", "minecraft:sea_pickle", 16, "Sea Pickles"),
    ("give", "minecraft:lily_pad", 16, "Lily Pads"),
    ("stat", "minecraft:swim_one_cm", 50000, "Strong Swimmer"),
    ("stat", "minecraft:walk_under_water_one_cm", 20000, "Seafloor Stroll"),
    ("struct", "minecraft:shipwreck", 1, "Shipwrecked"),
    ("struct", "minecraft:ocean_ruin_warm", 1, "Warm Ruins"),
    ("struct", "minecraft:ocean_ruin_cold", 1, "Cold Ruins"),
    ("struct", "minecraft:monument", 1, "Ocean Monument"),
    ("give", "minecraft:prismarine_shard", 32, "Prismarine Shards"),
    ("give", "minecraft:prismarine_crystals", 16, "Prismarine Crystals"),
    ("craft", "minecraft:prismarine_bricks", 32, "Prismarine Bricks"),
    ("craft", "minecraft:dark_prismarine", 16, "Dark Prismarine"),
    ("have", "minecraft:wet_sponge", 4, "Soaked Sponges"),
    ("have", "minecraft:heart_of_the_sea", 1, "Heart of the Sea"),
    ("craft", "minecraft:conduit", 1, "Conduit Power"),
    ("kill", "minecraft:squid", 10, "Squid Hunt"),
    ("give", "minecraft:turtle_scute", 4, "Turtle Scutes"),
    ("craft", "minecraft:turtle_helmet", 1, "Turtle Shell"),
    ("adv", "minecraft:husbandry/tactical_fishing", 1, "Tactical Fishing"),
    ("have", "minecraft:cod_bucket", 1, "Cod in a Bucket"),
    ("have", "minecraft:salmon_bucket", 1, "Salmon in a Bucket"),
    ("have", "minecraft:pufferfish_bucket", 1, "Puffer in a Bucket"),
    ("have", "minecraft:tropical_fish_bucket", 1, "Aquarium Fish"),
    ("adv", "minecraft:husbandry/axolotl_in_a_bucket", 1, "The Cutest Predator"),
    ("adv", "minecraft:husbandry/kill_axolotl_target", 1, "The Healing Power of Friendship!"),
    ("adv", "minecraft:husbandry/tadpole_in_a_bucket", 1, "Bukkit Bukkit"),
    ("have", "minecraft:ochre_froglight", 1, "Ochre Froglight"),
    ("have", "minecraft:verdant_froglight", 1, "Verdant Froglight"),
    ("have", "minecraft:pearlescent_froglight", 1, "Pearlescent Froglight"),
    ("adv", "minecraft:husbandry/froglights", 1, "With Our Powers Combined!"),
    ("adv", "minecraft:husbandry/leash_all_frog_variants", 1, "When the Squad Hops into Town"),
    ("adv", "minecraft:husbandry/tame_an_animal", 1, "Best Friends Forever"),
    ("give", "minecraft:bone", 32, "Treats for the Pack"),
    ("give", "minecraft:armadillo_scute", 8, "Armadillo Scutes"),
    ("craft", "minecraft:wolf_armor", 1, "Wolf Armour"),
    ("adv", "minecraft:husbandry/repair_wolf_armor", 1, "Good as New"),
    ("adv", "minecraft:husbandry/remove_wolf_armor", 1, "Shear Brilliance"),
    ("have", "minecraft:saddle", 1, "Saddle Up"),
    ("stat", "minecraft:horse_one_cm", 100000, "Horseback Rider"),
    ("craft", "minecraft:leather_horse_armor", 1, "Leather Barding"),
    ("have", "minecraft:golden_horse_armor", 1, "Golden Barding"),
    ("have", "minecraft:diamond_horse_armor", 1, "Diamond Barding"),
    ("craft", "minecraft:carrot_on_a_stick", 1, "Carrot on a Stick"),
    ("stat", "minecraft:pig_one_cm", 2000, "When Pigs Ride"),
    ("adv", "minecraft:husbandry/ride_a_boat_with_a_goat", 1, "Whatever Floats Your Goat!"),
    ("have", "minecraft:goat_horn", 1, "Goat Horn"),
    ("give", "minecraft:rabbit_foot", 2, "Lucky Foot"),
    ("adv", "minecraft:husbandry/allay_deliver_item_to_player", 1, "You've Got a Friend in Me"),
    ("adv", "minecraft:husbandry/allay_deliver_cake_to_note_block", 1, "Birthday Song"),
    ("have", "minecraft:sniffer_egg", 1, "Ancient Egg"),
    ("adv", "minecraft:husbandry/obtain_sniffer_egg", 1, "Smells Interesting"),
    ("adv", "minecraft:husbandry/feed_snifflet", 1, "Little Sniffs"),
    ("give", "minecraft:torchflower_seeds", 4, "Torchflower Seeds"),
    ("give", "minecraft:pitcher_pod", 2, "Pitcher Pods"),
    ("adv", "minecraft:husbandry/plant_any_sniffer_seed", 1, "Planting the Past"),
    ("give", "minecraft:torchflower", 4, "Torchflowers"),
    ("give", "minecraft:pitcher_plant", 2, "Pitcher Plants"),
    ("stat", "minecraft:animals_bred", 75, "Breeder's Pride"),
    ("adv", "minecraft:husbandry/bred_all_animals", 1, "Two by Two"),
    ("stat", "minecraft:fish_caught", 50, "Seasoned Angler"),
    ("give", "minecraft:cooked_cod", 32, "Fish & Chips"),
    ("give", "minecraft:cooked_salmon", 32, "Grilled Salmon"),
    ("have", "minecraft:name_tag", 1, "What's in a Name"),
    ("have", "minecraft:enchanted_book", 1, "Fished Treasure"),
    ("have", "minecraft:bow", 1, "Lucky Bow"),
    ("stat", "minecraft:boat_one_cm", 500000, "Admiral"),
    ("stat", "minecraft:horse_one_cm", 500000, "Cavalry"),
    ("stat", "minecraft:swim_one_cm", 200000, "Channel Crossing"),
    ("give", "minecraft:white_wool", 64, "Flock Keeper"),
    ("give", "minecraft:black_wool", 16, "Black Sheep"),
    ("give", "minecraft:brown_wool", 16, "Brown Fleece"),
    ("give", "minecraft:gray_wool", 16, "Grey Fleece"),
    ("give", "minecraft:pink_wool", 8, "Pink Fleece"),
    ("craft", "minecraft:lime_dye", 16, "Lime Dye"),
    ("craft", "minecraft:light_blue_dye", 16, "Sky Dye"),
    ("craft", "minecraft:magenta_dye", 16, "Magenta Dye"),
    ("give", "minecraft:honey_block", 4, "Honey Blocks"),
    ("craft", "minecraft:beehive", 2, "Apiary"),
    ("adv", "minecraft:husbandry/silk_touch_nest", 1, "Total Beelocation"),
    ("stat", "minecraft:fish_caught", 100, "Master Angler"),
    ("stat", "minecraft:animals_bred", 150, "Ranch Owner"),
    ("adv", "minecraft:husbandry/whole_pack", 1, "The Whole Pack"),
    ("adv", "minecraft:husbandry/complete_catalogue", 1, "A Complete Catalogue"),
    ("stat", "minecraft:fish_caught", 200, "Legend of the Lake"),
    ("xp", "", 25, "Tidecaller"),
])

# ------------------------------------------------------------------ V. INTO THE NETHER
chapter("Ledger V: Into the Nether", "&c", "minecraft:netherrack", "Fire, fortune and ancient debris. Bring a sword.", [
    ("craft", "minecraft:flint_and_steel", 1, "Strike a Light"),
    ("dim", "minecraft:the_nether", 1, "Gateway to the Nether"),
    ("biome", "minecraft:nether_wastes", 1, "Nether Wastes"),
    ("give", "minecraft:netherrack", 128, "Netherrack Haul"),
    ("kill", "minecraft:zombified_piglin", 20, "Pigmen Patrol"),
    ("give", "minecraft:quartz", 64, "Nether Quartz"),
    ("craft", "minecraft:quartz_block", 16, "Quartz Blocks"),
    ("craft", "minecraft:quartz_pillar", 8, "Quartz Pillars"),
    ("have", "minecraft:smooth_quartz", 16, "Smooth Quartz"),
    ("give", "minecraft:glowstone_dust", 32, "Glowstone Dust"),
    ("give", "minecraft:glowstone", 16, "Glowstone Blocks"),
    ("give", "minecraft:magma_block", 16, "Magma Blocks"),
    ("kill", "minecraft:magma_cube", 15, "Magma Cubes"),
    ("give", "minecraft:magma_cream", 8, "Magma Cream"),
    ("biome", "minecraft:crimson_forest", 1, "Crimson Forest"),
    ("give", "minecraft:crimson_stem", 64, "Crimson Stems"),
    ("give", "minecraft:crimson_fungus", 8, "Crimson Fungus"),
    ("give", "minecraft:nether_wart_block", 16, "Wart Blocks"),
    ("give", "minecraft:weeping_vines", 16, "Weeping Vines"),
    ("give", "minecraft:shroomlight", 8, "Shroomlights"),
    ("kill", "minecraft:hoglin", 10, "Hoglin Hunt"),
    ("give", "minecraft:cooked_porkchop", 32, "Hoglin Roast"),
    ("biome", "minecraft:warped_forest", 1, "Warped Forest"),
    ("give", "minecraft:warped_stem", 64, "Warped Stems"),
    ("give", "minecraft:warped_fungus", 8, "Warped Fungus"),
    ("give", "minecraft:warped_wart_block", 16, "Warped Wart"),
    ("give", "minecraft:twisting_vines", 16, "Twisting Vines"),
    ("craft", "minecraft:warped_fungus_on_a_stick", 1, "Fungus on a Stick"),
    ("adv", "minecraft:nether/ride_strider", 1, "This Boat Has Legs"),
    ("stat", "minecraft:strider_one_cm", 10000, "Lava Surfer"),
    ("biome", "minecraft:soul_sand_valley", 1, "Soul Sand Valley"),
    ("give", "minecraft:soul_sand", 64, "Soul Sand"),
    ("give", "minecraft:soul_soil", 64, "Soul Soil"),
    ("kill", "minecraft:ghast", 5, "Ghast Busters"),
    ("give", "minecraft:ghast_tear", 4, "Ghast Tears"),
    ("adv", "minecraft:nether/return_to_sender", 1, "Return to Sender"),
    ("adv", "minecraft:adventure/spyglass_at_ghast", 1, "Is It a Balloon?"),
    ("craft", "minecraft:soul_torch", 32, "Soul Torches"),
    ("craft", "minecraft:soul_lantern", 8, "Soul Lanterns"),
    ("craft", "minecraft:soul_campfire", 2, "Soul Campfire"),
    ("biome", "minecraft:basalt_deltas", 1, "Basalt Deltas"),
    ("give", "minecraft:basalt", 64, "Basalt Columns"),
    ("give", "minecraft:blackstone", 128, "Blackstone"),
    ("craft", "minecraft:polished_blackstone_bricks", 64, "Blackstone Bricks"),
    ("craft", "minecraft:chiseled_polished_blackstone", 8, "Carved Blackstone"),
    ("adv", "minecraft:nether/explore_nether", 1, "Hot Tourist Destinations"),
    ("struct", "minecraft:fortress", 1, "A Terrible Fortress"),
    ("give", "minecraft:nether_brick", 64, "Nether Brick"),
    ("craft", "minecraft:nether_bricks", 32, "Nether Brick Blocks"),
    ("give", "minecraft:nether_wart", 32, "Nether Wart"),
    ("craft", "minecraft:red_nether_bricks", 32, "Red Nether Bricks"),
    ("kill", "minecraft:blaze", 10, "Blaze Runner"),
    ("give", "minecraft:blaze_rod", 16, "Blaze Rods"),
    ("craft", "minecraft:blaze_powder", 16, "Blaze Powder"),
    ("kill", "minecraft:wither_skeleton", 15, "Black Bones"),
    ("give", "minecraft:charcoal", 64, "Charcoal Burner"),
    ("have", "minecraft:wither_skeleton_skull", 1, "Spooky Scary Skeleton"),
    ("struct", "minecraft:bastion_remnant", 1, "Those Were the Days"),
    ("give", "minecraft:gold_nugget", 64, "Piglin Bait"),
    ("adv", "minecraft:nether/distract_piglin", 1, "Oh Shiny"),
    ("kill", "minecraft:piglin", 20, "Piglin Raid"),
    ("kill", "minecraft:piglin_brute", 3, "Brute Force"),
    ("adv", "minecraft:nether/loot_bastion", 1, "War Pigs"),
    ("give", "minecraft:gilded_blackstone", 4, "Gilded Blackstone"),
    ("have", "minecraft:crying_obsidian", 8, "Who is Cutting Onions?"),
    ("craft", "minecraft:respawn_anchor", 1, "Respawn Anchor"),
    ("adv", "minecraft:nether/charge_respawn_anchor", 1, "Not Quite Nine Lives"),
    ("craft", "minecraft:lodestone", 1, "Lodestone"),
    ("adv", "minecraft:nether/use_lodestone", 1, "Country Lode, Take Me Home"),
    ("adv", "minecraft:nether/fast_travel", 1, "Subspace Bubble"),
    ("struct", "minecraft:nether_fossil", 1, "Nether Fossil"),
    ("give", "minecraft:bone_block", 16, "Fossil Bones"),
    ("kill", "minecraft:zoglin", 3, "Zoglin Slayer"),
    ("give", "minecraft:ancient_debris", 4, "Hidden in the Depths"),
    ("give", "minecraft:netherite_scrap", 4, "Netherite Scrap"),
    ("have", "minecraft:netherite_upgrade_smithing_template", 1, "Upgrade Template"),
    ("have", "minecraft:netherite_sword", 1, "Netherite Blade"),
    ("have", "minecraft:netherite_pickaxe", 1, "Netherite Pick"),
    ("give", "minecraft:crimson_planks", 64, "Crimson Carpentry"),
    ("give", "minecraft:warped_planks", 64, "Warped Carpentry"),
    ("give", "minecraft:soul_sand", 128, "Soul Harvest"),
    ("kill", "minecraft:blaze", 30, "Blaze Hunter"),
    ("give", "minecraft:blaze_rod", 48, "Rod Collector"),
    ("kill", "minecraft:ghast", 15, "Sky Wail"),
    ("kill", "minecraft:wither_skeleton", 40, "Bone Breaker"),
    ("have", "minecraft:wither_skeleton_skull", 3, "Three Skulls"),
    ("kill", "minecraft:hoglin", 30, "Hoglin Herd"),
    ("kill", "minecraft:magma_cube", 50, "Magma Melter"),
    ("kill", "minecraft:zombified_piglin", 75, "Pigmen Purge"),
    ("give", "minecraft:quartz", 256, "Quartz Fortune"),
    ("give", "minecraft:glowstone", 64, "Glowstone Hoard"),
    ("give", "minecraft:shroomlight", 32, "Shroomlight Garden"),
    ("give", "minecraft:magma_cream", 32, "Magma Stockpile"),
    ("give", "minecraft:gilded_blackstone", 16, "Golden Ruins"),
    ("give", "minecraft:netherite_scrap", 12, "Scrap Heap"),
    ("adv", "minecraft:nether/ride_strider_in_overworld_lava", 1, "Feels Like Home"),
    ("adv", "minecraft:nether/uneasy_alliance", 1, "Uneasy Alliance"),
    ("have", "minecraft:music_disc_pigstep", 1, "Pigstep"),
    ("stat", "minecraft:strider_one_cm", 50000, "Lava Admiral"),
    ("craft", "minecraft:polished_basalt", 64, "Polished Basalt"),
    ("adv", "minecraft:nether/netherite_armor", 1, "Cover Me in Debris"),
    ("xp", "", 30, "Hellfire Veteran"),
])

# ------------------------------------------------------------------ VI. ARCANE ARTS
POT = lambda p, t: ("pot", ("minecraft:potion", "minecraft:" + p), 1, t)
SPL = lambda p, t: ("pot", ("minecraft:splash_potion", "minecraft:" + p), 1, t)
LNG = lambda p, t: ("pot", ("minecraft:lingering_potion", "minecraft:" + p), 1, t)
BK = lambda e, lvl, t: ("book", ("minecraft:" + e, lvl), 1, t)
chapter("Ledger VI: Arcane Arts", "&d", "minecraft:brewing_stand", "Brewers and enchanters, the Ledger rewards true mastery.", [
    ("craft", "minecraft:brewing_stand", 1, "The Brewing Stand"),
    ("craft", "minecraft:glass_bottle", 16, "Empty Bottles"),
    ("adv", "minecraft:nether/brew_potion", 1, "Local Brewery"),
    POT("awkward", "Awkward Beginnings"),
    POT("night_vision", "Eyes of the Night"),
    POT("invisibility", "Now You See Me"),
    POT("leaping", "Leap of Faith"),
    POT("fire_resistance", "Fireproof"),
    POT("swiftness", "Quicksilver"),
    POT("water_breathing", "Gills"),
    POT("healing", "First Aid"),
    POT("regeneration", "Second Wind"),
    POT("strength", "Liquid Courage"),
    POT("slow_falling", "Feather Fall"),
    POT("poison", "Venom"),
    POT("weakness", "Sap Strength"),
    POT("harming", "Bottled Pain"),
    POT("slowness", "Molasses"),
    POT("turtle_master", "Turtle Master"),
    POT("long_night_vision", "Long Night"),
    POT("long_invisibility", "Ghost Walk"),
    POT("strong_swiftness", "Lightning Feet"),
    POT("strong_strength", "Titan's Draught"),
    POT("strong_healing", "Greater Healing"),
    POT("strong_regeneration", "Phoenix Tears"),
    POT("strong_leaping", "Moon Boots"),
    SPL("healing", "Splash of Life"),
    SPL("harming", "Splash of Doom"),
    SPL("weakness", "Cure Prep"),
    LNG("regeneration", "Healing Cloud"),
    LNG("poison", "Toxic Cloud"),
    ("craft", "minecraft:fermented_spider_eye", 4, "Fermented Eyes"),
    ("craft", "minecraft:glistering_melon_slice", 4, "Glistering Melon"),
    ("give", "minecraft:sugar", 32, "Swiftness Sugar"),
    ("give", "minecraft:spider_eye", 16, "Spider Eyes"),
    ("give", "minecraft:phantom_membrane", 8, "Phantom Membrane"),
    ("give", "minecraft:pufferfish", 4, "Puffer Venom"),
    ("give", "minecraft:honey_bottle", 16, "Honeyed Tonic"),
    ("give", "minecraft:gunpowder", 32, "Gunpowder"),
    ("stat", "minecraft:interact_with_brewingstand", 25, "Brewmaster"),
    ("craft", "minecraft:golden_apple", 2, "Golden Apples"),
    ("adv", "minecraft:story/cure_zombie_villager", 1, "Zombie Doctor"),
    ("adv", "minecraft:story/enchant_item", 1, "Enchanter"),
    ("stat", "minecraft:enchant_item", 10, "Apprentice Enchanter"),
    ("give", "minecraft:book", 16, "Spellbooks"),
    ("craft", "minecraft:lapis_block", 8, "Lapis Blocks"),
    ("have", "minecraft:experience_bottle", 16, "Bottled Wisdom"),
    BK("unbreaking", 3, "Unbreaking III"),
    BK("efficiency", 5, "Efficiency V"),
    BK("fortune", 3, "Fortune III"),
    BK("silk_touch", 1, "Silk Touch"),
    BK("sharpness", 5, "Sharpness V"),
    BK("smite", 5, "Smite V"),
    BK("bane_of_arthropods", 5, "Bane of Arthropods V"),
    BK("looting", 3, "Looting III"),
    BK("sweeping_edge", 3, "Sweeping Edge III"),
    BK("fire_aspect", 2, "Fire Aspect II"),
    BK("knockback", 2, "Knockback II"),
    BK("protection", 4, "Protection IV"),
    BK("fire_protection", 4, "Fire Protection IV"),
    BK("blast_protection", 4, "Blast Protection IV"),
    BK("projectile_protection", 4, "Projectile Protection IV"),
    BK("feather_falling", 4, "Feather Falling IV"),
    BK("respiration", 3, "Respiration III"),
    BK("aqua_affinity", 1, "Aqua Affinity"),
    BK("depth_strider", 3, "Depth Strider III"),
    BK("thorns", 3, "Thorns III"),
    BK("power", 5, "Power V"),
    BK("punch", 2, "Punch II"),
    BK("flame", 1, "Flame"),
    BK("infinity", 1, "Infinity"),
    BK("multishot", 1, "Multishot"),
    BK("piercing", 4, "Piercing IV"),
    BK("quick_charge", 3, "Quick Charge III"),
    BK("loyalty", 3, "Loyalty III"),
    BK("riptide", 3, "Riptide III"),
    BK("channeling", 1, "Channeling"),
    BK("impaling", 5, "Impaling V"),
    BK("luck_of_the_sea", 3, "Luck of the Sea III"),
    BK("lure", 3, "Lure III"),
    BK("mending", 1, "Mending"),
    BK("frost_walker", 2, "Frost Walker II"),
    BK("soul_speed", 3, "Soul Speed III"),
    BK("density", 5, "Density V"),
    BK("breach", 4, "Breach IV"),
    BK("wind_burst", 1, "Wind Burst"),
    BK("swift_sneak", 3, "Swift Sneak III"),
    ("stat", "minecraft:enchant_item", 50, "Journeyman Enchanter"),
    ("xp", "", 35, "Level Thirty-Five"),
    ("kill", "minecraft:vex", 15, "Spirits of the Evoker"),
    ("have", "minecraft:enchanted_golden_apple", 1, "Notch's Apple"),
    ("give", "minecraft:glowstone_dust", 64, "Amplifier Stock"),
    ("give", "minecraft:nether_wart", 64, "Brewer's Stock"),
    ("give", "minecraft:blaze_powder", 32, "Fuel Stock"),
    ("give", "minecraft:fermented_spider_eye", 8, "Corruption Stock"),
    ("stat", "minecraft:interact_with_brewingstand", 100, "Potion Factory"),
    ("stat", "minecraft:enchant_item", 150, "Archmage of the Table"),
    ("xp", "", 40, "Arcane Ascension"),
    ("adv", "minecraft:nether/all_potions", 1, "A Furious Cocktail"),
    ("xp", "", 50, "Fifty Levels Deep"),
])

# ------------------------------------------------------------------ VII. THE DEEP BELOW
SH = lambda s, t: ("have", "minecraft:%s_pottery_sherd" % s, 1, t)
TR = lambda s, t: ("have", "minecraft:%s_armor_trim_smithing_template" % s, 1, t)
chapter("Ledger VII: The Deep Below", "&3", "minecraft:sculk_shrieker", "Caves, ruins and trial vaults. What sleeps below pays in gold.", [
    ("biome", "minecraft:dripstone_caves", 1, "Dripstone Caves"),
    ("give", "minecraft:pointed_dripstone", 16, "Stalactites"),
    ("give", "minecraft:dripstone_block", 32, "Dripstone Blocks"),
    ("biome", "minecraft:lush_caves", 1, "Lush Caves"),
    ("give", "minecraft:moss_block", 32, "Moss Blocks"),
    ("craft", "minecraft:moss_carpet", 32, "Moss Carpet"),
    ("give", "minecraft:glow_lichen", 16, "Glow Lichen"),
    ("give", "minecraft:azalea", 4, "Azalea"),
    ("give", "minecraft:flowering_azalea", 4, "Flowering Azalea"),
    ("give", "minecraft:big_dripleaf", 8, "Big Dripleaf"),
    ("give", "minecraft:small_dripleaf", 8, "Small Dripleaf"),
    ("give", "minecraft:hanging_roots", 8, "Hanging Roots"),
    ("give", "minecraft:rooted_dirt", 16, "Rooted Dirt"),
    ("have", "minecraft:spore_blossom", 1, "Spore Blossom"),
    ("struct", "minecraft:mineshaft", 1, "Abandoned Mineshaft"),
    ("give", "minecraft:cobbled_deepslate", 128, "Deepslate Quarry"),
    ("give", "minecraft:tuff", 64, "Tuff Quarry"),
    ("craft", "minecraft:raw_copper_block", 8, "Raw Copper Blocks"),
    ("craft", "minecraft:raw_iron_block", 4, "Raw Iron Blocks"),
    ("craft", "minecraft:raw_gold_block", 2, "Raw Gold Blocks"),
    ("craft", "minecraft:coal_block", 16, "Coal Blocks"),
    ("craft", "minecraft:amethyst_block", 8, "Amethyst Blocks"),
    ("give", "minecraft:coarse_dirt", 32, "Excavation Spoil"),
    ("adv", "minecraft:adventure/salvage_sherd", 1, "Respecting the Remnants"),
    SH("angler", "Angler Sherd"), SH("archer", "Archer Sherd"), SH("arms_up", "Arms Up Sherd"),
    SH("blade", "Blade Sherd"), SH("brewer", "Brewer Sherd"), SH("burn", "Burn Sherd"),
    SH("danger", "Danger Sherd"), SH("explorer", "Explorer Sherd"), SH("friend", "Friend Sherd"),
    SH("heart", "Heart Sherd"), SH("heartbreak", "Heartbreak Sherd"), SH("howl", "Howl Sherd"),
    SH("miner", "Miner Sherd"), SH("mourner", "Mourner Sherd"), SH("plenty", "Plenty Sherd"),
    SH("prize", "Prize Sherd"), SH("sheaf", "Sheaf Sherd"), SH("shelter", "Shelter Sherd"),
    SH("skull", "Skull Sherd"), SH("snort", "Snort Sherd"), SH("flow", "Flow Sherd"),
    SH("guster", "Guster Sherd"), SH("scrape", "Scrape Sherd"),
    ("adv", "minecraft:adventure/craft_decorated_pot_using_only_sherds", 1, "Careful Restoration"),
    ("struct", "minecraft:trial_chambers", 1, "Trial Chambers"),
    ("adv", "minecraft:adventure/minecraft_trials_edition", 1, "Minecraft: Trial(s) Edition"),
    ("adv", "minecraft:adventure/under_lock_and_key", 1, "Under Lock and Key"),
    ("give", "minecraft:breeze_rod", 16, "Breeze Rods"),
    ("give", "minecraft:wind_charge", 32, "Wind Charges"),
    ("adv", "minecraft:adventure/blowback", 1, "Blowback"),
    ("adv", "minecraft:adventure/who_needs_rockets", 1, "Who Needs Rockets?"),
    ("have", "minecraft:ominous_trial_key", 1, "Ominous Key"),
    ("have", "minecraft:ominous_bottle", 1, "Ominous Bottle"),
    ("adv", "minecraft:adventure/revaulting", 1, "Revaulting"),
    ("have", "minecraft:heavy_core", 1, "Heavy Core"),
    ("craft", "minecraft:mace", 1, "Smash Hit"),
    ("adv", "minecraft:adventure/overoverkill", 1, "Over-Overkill"),
    ("have", "minecraft:music_disc_creator", 1, "Creator"),
    ("have", "minecraft:music_disc_precipice", 1, "Precipice"),
    ("biome", "minecraft:deep_dark", 1, "The Deep Dark"),
    ("struct", "minecraft:ancient_city", 1, "Ancient City"),
    ("give", "minecraft:sculk", 32, "Sculk"),
    ("give", "minecraft:sculk_vein", 16, "Sculk Veins"),
    ("give", "minecraft:sculk_sensor", 4, "Sculk Sensors"),
    ("have", "minecraft:sculk_catalyst", 1, "Sculk Catalyst"),
    ("have", "minecraft:sculk_shrieker", 1, "Sculk Shrieker"),
    ("craft", "minecraft:calibrated_sculk_sensor", 1, "Calibrated Sensor"),
    ("adv", "minecraft:adventure/avoid_vibration", 1, "Sneak 100"),
    ("adv", "minecraft:adventure/kill_mob_near_sculk_catalyst", 1, "It Spreads"),
    ("craft", "minecraft:recovery_compass", 1, "Recovery Compass"),
    ("have", "minecraft:disc_fragment_5", 9, "Disc Fragments"),
    ("craft", "minecraft:music_disc_5", 1, "Disc 5"),
    ("have", "minecraft:music_disc_otherside", 1, "Otherside"),
    ("adv", "minecraft:adventure/trim_with_any_armor_pattern", 1, "Crafting a New Look"),
    TR("coast", "Coast Trim"), TR("dune", "Dune Trim"), TR("wild", "Wild Trim"),
    TR("sentry", "Sentry Trim"), TR("vex", "Vex Trim"), TR("tide", "Tide Trim"),
    TR("ward", "Ward Trim"), TR("silence", "Silence Trim"), TR("wayfinder", "Wayfinder Trim"),
    TR("shaper", "Shaper Trim"), TR("raiser", "Raiser Trim"), TR("host", "Host Trim"),
    TR("flow", "Flow Trim"), TR("bolt", "Bolt Trim"),
    ("give", "minecraft:granite", 128, "Granite Seam"),
    ("give", "minecraft:diorite", 128, "Diorite Seam"),
    ("give", "minecraft:andesite", 128, "Andesite Seam"),
    ("give", "minecraft:gravel", 128, "Gravel Seam"),
    ("give", "minecraft:clay_ball", 64, "Clay Seam"),
    ("give", "minecraft:smooth_basalt", 32, "Geode Crust"),
    ("give", "minecraft:breeze_rod", 48, "Gale Harvest"),
    ("have", "minecraft:heavy_core", 2, "Twin Cores"),
    ("give", "minecraft:sculk", 128, "Sculk Harvest"),
    ("xp", "", 45, "Deep Delver"),
])

# ------------------------------------------------------------------ VIII. BOUNTY BOARD
chapter("Ledger VIII: Bounty Board", "&4", "minecraft:iron_sword", "Raids, trophies and battle-tested gear. Combat pays.", [
    ("adv", "minecraft:adventure/kill_a_mob", 1, "Monster Hunter's Oath"),
    ("adv", "minecraft:adventure/shoot_arrow", 1, "Take Aim"),
    ("craft", "minecraft:arrow", 64, "Quiver Full"),
    ("craft", "minecraft:spectral_arrow", 16, "Spectral Arrows"),
    ("craft", "minecraft:target", 2, "Archery Range"),
    ("stat", "minecraft:target_hit", 20, "Bullseye Practice"),
    ("adv", "minecraft:adventure/bullseye", 1, "Bullseye"),
    ("craft", "minecraft:iron_helmet", 1, "Iron Helm"),
    ("craft", "minecraft:iron_leggings", 1, "Iron Greaves"),
    ("craft", "minecraft:iron_boots", 1, "Iron Boots"),
    ("craft", "minecraft:iron_sword", 1, "Iron Sword"),
    ("craft", "minecraft:iron_axe", 1, "Iron Axe"),
    ("have", "minecraft:chainmail_chestplate", 1, "Chainmail"),
    ("craft", "minecraft:golden_helmet", 1, "Golden Crown"),
    ("craft", "minecraft:golden_sword", 1, "Gilded Blade"),
    ("give", "minecraft:rotten_flesh", 64, "Rotten Spoils"),
    ("give", "minecraft:bone", 64, "Bone Pile"),
    ("give", "minecraft:gunpowder", 64, "Powder Keg"),
    ("give", "minecraft:spider_eye", 32, "Eyes of the Swarm"),
    ("give", "minecraft:slime_ball", 32, "Slime Balls"),
    ("give", "minecraft:arrow", 64, "Spent Arrows"),
    ("kill", "minecraft:zombie_villager", 10, "Lost Villagers"),
    ("kill", "minecraft:endermite", 3, "Endermites"),
    ("stat", "minecraft:mob_kills", 100, "Hundred Kills"),
    ("stat", "minecraft:damage_dealt", 10000, "Heavy Hitter"),
    ("stat", "minecraft:damage_blocked_by_shield", 1000, "Shield Wall"),
    ("adv", "minecraft:adventure/sniper_duel", 1, "Sniper Duel"),
    ("adv", "minecraft:adventure/two_birds_one_arrow", 1, "Two Birds, One Arrow"),
    ("adv", "minecraft:adventure/ol_betsy", 1, "Ol' Betsy"),
    ("adv", "minecraft:adventure/whos_the_pillager_now", 1, "Who's the Pillager Now?"),
    ("adv", "minecraft:adventure/arbalistic", 1, "Arbalistic"),
    ("adv", "minecraft:adventure/throw_trident", 1, "A Throwaway Joke"),
    ("have", "minecraft:trident", 1, "Trident"),
    ("adv", "minecraft:adventure/very_very_frightening", 1, "Very Very Frightening"),
    ("adv", "minecraft:adventure/summon_iron_golem", 1, "Hired Help"),
    ("adv", "minecraft:adventure/voluntary_exile", 1, "Voluntary Exile"),
    ("stat", "minecraft:raid_trigger", 1, "Bad Omen"),
    ("stat", "minecraft:raid_win", 1, "Raid Victor"),
    ("adv", "minecraft:adventure/hero_of_the_village", 1, "Hero of the Village"),
    ("have", "minecraft:bell", 1, "Ring the Alarm"),
    ("adv", "minecraft:adventure/totem_of_undying", 1, "Postmortal"),
    ("have", "minecraft:white_banner", 1, "Captured Banner"),
    ("have", "minecraft:skeleton_skull", 1, "Skeleton Skull"),
    ("have", "minecraft:zombie_head", 1, "Zombie Head"),
    ("have", "minecraft:creeper_head", 1, "Creeper Head"),
    ("have", "minecraft:piglin_head", 1, "Piglin Head"),
    ("craft", "minecraft:diamond_helmet", 1, "Diamond Helm"),
    ("craft", "minecraft:diamond_leggings", 1, "Diamond Greaves"),
    ("craft", "minecraft:diamond_boots", 1, "Diamond Boots"),
    ("craft", "minecraft:diamond_axe", 1, "Diamond Axe"),
    ("craft", "minecraft:diamond_pickaxe", 1, "Diamond Pickaxe"),
    ("craft", "minecraft:diamond_shovel", 1, "Diamond Shovel"),
    ("craft", "minecraft:diamond_hoe", 1, "Diamond Hoe"),
    ("stat", "minecraft:mob_kills", 250, "Quarter Thousand"),
    ("stat", "minecraft:damage_taken", 10000, "Battle Scars"),
    ("kill", "minecraft:zombie_villager", 30, "Outbreak"),
    ("kill", "minecraft:vex", 40, "Vex Exorcist"),
    ("kill", "minecraft:endermite", 15, "Pest Control"),
    ("stat", "minecraft:raid_win", 3, "Raid Veteran"),
    ("stat", "minecraft:raid_trigger", 3, "Omen Seeker"),
    ("give", "minecraft:rotten_flesh", 256, "Zombie Graveyard"),
    ("give", "minecraft:bone", 256, "Ossuary"),
    ("give", "minecraft:gunpowder", 256, "Powder Magazine"),
    ("give", "minecraft:slime_ball", 64, "Slime Vat"),
    ("give", "minecraft:spider_eye", 64, "Eye Collection"),
    ("give", "minecraft:cobweb", 16, "Web Weaver"),
    ("give", "minecraft:phantom_membrane", 24, "Night Hunter"),
    ("give", "minecraft:flint", 64, "Flint Knapper"),
    ("craft", "minecraft:tipped_arrow", 16, "Tipped Arrows"),
    ("stat", "minecraft:target_hit", 100, "Sharpshooter"),
    ("stat", "minecraft:mob_kills", 500, "Five Hundred"),
    ("stat", "minecraft:damage_dealt", 50000, "Warlord's Strength"),
    ("stat", "minecraft:damage_blocked_by_shield", 5000, "Iron Bulwark"),
    ("stat", "minecraft:damage_taken", 50000, "Unbreakable"),
    ("give", "minecraft:wither_rose", 4, "Wither Roses"),
    ("have", "minecraft:soul_sand", 4, "Soul Altar"),
    ("adv", "minecraft:nether/summon_wither", 1, "Withering Heights"),
    ("kill", "minecraft:wither", 1, "The Wither"),
    ("have", "minecraft:nether_star", 1, "Nether Star"),
    ("stat", "minecraft:raid_win", 5, "Raid Lord"),
    ("stat", "minecraft:mob_kills", 1000, "One Thousand Kills"),
    ("kill", "minecraft:wither", 3, "Wither Slayer"),
    ("have", "minecraft:nether_star", 3, "Star Collector"),
    ("stat", "minecraft:mob_kills", 2500, "Living Legend"),
    ("stat", "minecraft:damage_dealt", 200000, "Unstoppable"),
    ("have", "minecraft:chainmail_helmet", 1, "Chain Coif"),
    ("have", "minecraft:chainmail_leggings", 1, "Chain Leggings"),
    ("have", "minecraft:chainmail_boots", 1, "Chain Boots"),
    ("give", "minecraft:arrow", 256, "Armoury Arrows"),
    ("craft", "minecraft:iron_pickaxe", 1, "Iron Pickaxe"),
    ("craft", "minecraft:golden_chestplate", 1, "Gilded Chestplate"),
    ("give", "minecraft:firework_rocket", 32, "Crossbow Fireworks"),
    ("give", "minecraft:tnt", 16, "Demolition Crew"),
    ("stat", "minecraft:mob_kills", 5000, "Bounty King"),
    ("xp", "", 55, "Battle Hardened"),
])

# ------------------------------------------------------------------ IX. THE FAR END
chapter("Ledger IX: The Far End", "&5", "minecraft:end_crystal", "Beyond the stronghold lies the void, a dragon and the cities of the End.", [
    ("craft", "minecraft:ender_eye", 12, "Eyes of Ender"),
    ("struct", "minecraft:stronghold", 1, "The Stronghold"),
    ("adv", "minecraft:story/follow_ender_eye", 1, "Eye Spy"),
    ("dim", "minecraft:the_end", 1, "The End?"),
    ("biome", "minecraft:the_end", 1, "Dragon's Isle"),
    ("give", "minecraft:end_stone", 128, "End Stone"),
    ("craft", "minecraft:end_stone_bricks", 64, "End Stone Bricks"),
    ("kill", "minecraft:ender_dragon", 1, "Free the End"),
    ("have", "minecraft:dragon_egg", 1, "The Next Generation"),
    ("have", "minecraft:dragon_breath", 4, "You Need a Mint"),
    ("craft", "minecraft:end_crystal", 4, "End Crystals"),
    ("adv", "minecraft:end/respawn_dragon", 1, "The End... Again..."),
    ("adv", "minecraft:end/enter_end_gateway", 1, "Remote Getaway"),
    ("biome", "minecraft:end_highlands", 1, "End Highlands"),
    ("biome", "minecraft:end_midlands", 1, "End Midlands"),
    ("biome", "minecraft:small_end_islands", 1, "Small End Islands"),
    ("biome", "minecraft:end_barrens", 1, "End Barrens"),
    ("give", "minecraft:chorus_fruit", 64, "Chorus Fruit"),
    ("have", "minecraft:popped_chorus_fruit", 32, "Popped Chorus"),
    ("give", "minecraft:chorus_flower", 4, "Chorus Flowers"),
    ("craft", "minecraft:purpur_block", 64, "Purpur Blocks"),
    ("craft", "minecraft:purpur_pillar", 16, "Purpur Pillars"),
    ("craft", "minecraft:purpur_stairs", 32, "Purpur Stairs"),
    ("struct", "minecraft:end_city", 1, "The City at the End of the Game"),
    ("kill", "minecraft:shulker", 10, "Shulker Hunt"),
    ("adv", "minecraft:end/levitate", 1, "Great View From Up Here"),
    ("give", "minecraft:shulker_shell", 4, "Shulker Shells"),
    ("craft", "minecraft:shulker_box", 1, "Shulker Box"),
    ("stat", "minecraft:open_shulker_box", 20, "Portable Storage"),
    ("have", "minecraft:elytra", 1, "Sky's the Limit"),
    ("craft", "minecraft:firework_rocket", 64, "Rocket Fuel"),
    ("stat", "minecraft:aviate_one_cm", 100000, "First Flight"),
    ("have", "minecraft:dragon_head", 1, "Dragon Head"),
    ("craft", "minecraft:end_rod", 16, "End Rods"),
    ("craft", "minecraft:ender_chest", 1, "Ender Chest"),
    ("stat", "minecraft:open_enderchest", 20, "Pocket Dimension"),
    ("craft", "minecraft:magenta_stained_glass", 32, "Void Glass"),
    ("craft", "minecraft:end_stone_brick_stairs", 64, "Void Stairway"),
    ("give", "minecraft:ender_eye", 32, "Eye Hoard"),
    ("give", "minecraft:end_stone", 512, "End Quarry"),
    ("craft", "minecraft:end_stone_brick_wall", 32, "Void Battlements"),
    ("craft", "minecraft:purpur_slab", 32, "Purpur Slabs"),
    ("craft", "minecraft:purple_shulker_box", 1, "Purple Shulker"),
    ("craft", "minecraft:black_shulker_box", 1, "Black Shulker"),
    ("craft", "minecraft:white_shulker_box", 1, "White Shulker"),
    ("craft", "minecraft:red_shulker_box", 1, "Red Shulker"),
    ("craft", "minecraft:lime_shulker_box", 1, "Lime Shulker"),
    ("craft", "minecraft:cyan_shulker_box", 1, "Cyan Shulker"),
    ("kill", "minecraft:shulker", 30, "Shell Shock"),
    ("give", "minecraft:shulker_shell", 16, "Shell Hoard"),
    ("craft", "minecraft:shulker_box", 4, "Storage Empire"),
    ("stat", "minecraft:aviate_one_cm", 1000000, "Ten Kilometre Glide"),
    ("have", "minecraft:dragon_breath", 16, "Dragon's Breath"),
    LNG("strong_harming", "Lingering Doom"),
    LNG("slow_falling", "Lingering Feathers"),
    ("have", "minecraft:elytra", 2, "Spare Wings"),
    ("kill", "minecraft:ender_dragon", 2, "Dragon Slayer"),
    ("craft", "minecraft:end_crystal", 8, "Crystal Array"),
    ("give", "minecraft:chorus_fruit", 256, "Chorus Orchard"),
    ("have", "minecraft:popped_chorus_fruit", 128, "Purpur Supply"),
    ("craft", "minecraft:purpur_block", 256, "Purpur Palace"),
    ("craft", "minecraft:end_stone_bricks", 256, "Void Fortress"),
    ("stat", "minecraft:fly_one_cm", 100000, "Air Time"),
    ("stat", "minecraft:fall_one_cm", 50000, "Freefall"),
    ("give", "minecraft:firework_rocket", 256, "Rocket Stockpile"),
    ("stat", "minecraft:open_enderchest", 100, "Void Banker"),
    ("stat", "minecraft:open_shulker_box", 100, "Box Master"),
    ("craft", "minecraft:end_stone_brick_slab", 64, "Void Floors"),
    ("craft", "minecraft:purple_concrete_powder", 64, "Void Concrete"),
    ("kill", "minecraft:shulker", 75, "Shulker Exterminator"),
    ("give", "minecraft:shulker_shell", 48, "Shell Fortune"),
    ("kill", "minecraft:ender_dragon", 3, "Dragonbane"),
    ("have", "minecraft:dragon_head", 2, "Twin Heads"),
    ("craft", "minecraft:purpur_pillar", 64, "Pillars of the Void"),
    ("give", "minecraft:crying_obsidian", 32, "Tears of the Void"),
    ("give", "minecraft:end_rod", 64, "Rod Lighthouse"),
    ("have", "minecraft:music_disc_11", 1, "Disc 11"),
    ("have", "minecraft:music_disc_13", 1, "Disc 13"),
    ("have", "minecraft:music_disc_cat", 1, "Cat"),
    ("have", "minecraft:music_disc_blocks", 1, "Blocks"),
    ("have", "minecraft:music_disc_chirp", 1, "Chirp"),
    ("have", "minecraft:music_disc_far", 1, "Far"),
    ("have", "minecraft:music_disc_mall", 1, "Mall"),
    ("have", "minecraft:music_disc_mellohi", 1, "Mellohi"),
    ("have", "minecraft:music_disc_stal", 1, "Stal"),
    ("have", "minecraft:music_disc_strad", 1, "Strad"),
    ("have", "minecraft:music_disc_ward", 1, "Ward"),
    ("have", "minecraft:music_disc_wait", 1, "Wait"),
    ("have", "minecraft:music_disc_relic", 1, "Relic"),
    ("have", "minecraft:music_disc_creator_music_box", 1, "Creator (Music Box)"),
    ("stat", "minecraft:play_record", 10, "DJ Set"),
    ("stat", "minecraft:aviate_one_cm", 5000000, "Fifty Kilometre Flight"),
    ("give", "minecraft:dragon_breath", 32, "Dragon Brewery"),
    ("stat", "minecraft:fly_one_cm", 500000, "High Flyer"),
    ("xp", "", 60, "Voidborn"),
])

# ------------------------------------------------------------------ X. LEGENDS OF THE REALM
chapter("Ledger X: Legends of the Realm", "&6&l", "minecraft:beacon", "Only true legends finish the Ledger. Long goals, the best pay.", [
    ("craft", "minecraft:iron_block", 64, "Iron Vault"),
    ("craft", "minecraft:lapis_block", 32, "Lapis Vault"),
    ("craft", "minecraft:redstone_block", 32, "Redstone Vault"),
    ("craft", "minecraft:coal_block", 64, "Coal Vault"),
    ("craft", "minecraft:copper_block", 64, "Copper Vault"),
    ("craft", "minecraft:diamond_block", 9, "Diamond Vault"),
    ("craft", "minecraft:beacon", 1, "Beacon of Hope"),
    ("adv", "minecraft:nether/create_beacon", 1, "Bring Home the Beacon"),
    ("adv", "minecraft:nether/create_full_beacon", 1, "Beaconator"),
    ("craft", "minecraft:beacon", 3, "Three Beacons"),
    ("craft", "minecraft:netherite_block", 1, "Netherite Block"),
    ("adv", "minecraft:husbandry/obtain_netherite_hoe", 1, "Serious Dedication"),
    ("have", "minecraft:netherite_helmet", 1, "Netherite Helm"),
    ("have", "minecraft:netherite_chestplate", 1, "Netherite Chestplate"),
    ("have", "minecraft:netherite_leggings", 1, "Netherite Leggings"),
    ("have", "minecraft:netherite_boots", 1, "Netherite Boots"),
    ("have", "minecraft:netherite_axe", 1, "Netherite Axe"),
    ("have", "minecraft:netherite_shovel", 1, "Netherite Shovel"),
    ("adv", "minecraft:adventure/trim_with_all_exclusive_armor_patterns", 1, "Smithing with Style"),
    ("adv", "minecraft:husbandry/balanced_diet", 1, "A Balanced Diet"),
    ("adv", "minecraft:adventure/adventuring_time", 1, "Adventuring Time"),
    ("adv", "minecraft:adventure/kill_all_mobs", 1, "Monsters Hunted"),
    ("adv", "minecraft:nether/all_effects", 1, "How Did We Get Here?"),
    ("have", "minecraft:enchanted_golden_apple", 3, "Golden Feast of Kings"),
    ("have", "minecraft:conduit", 2, "Twin Conduits"),
    ("have", "minecraft:nether_star", 5, "Five Stars"),
    ("have", "minecraft:heart_of_the_sea", 3, "Hearts of the Sea"),
    ("have", "minecraft:sniffer_egg", 3, "Sniffer Nursery"),
    ("have", "minecraft:heavy_core", 3, "Core Collector"),
    ("have", "minecraft:mace", 1, "Mace Bearer"),
    ("have", "minecraft:elytra", 3, "Wing Collection"),
    ("have", "minecraft:trident", 3, "Trident Trio"),
    ("have", "minecraft:dragon_head", 3, "Dragon Trophies"),
    ("have", "minecraft:wither_skeleton_skull", 6, "Skull Throne"),
    ("give", "minecraft:raw_iron_block", 64, "Iron Ore Tithe"),
    ("give", "minecraft:copper_ingot", 512, "Copper Tithe"),
    ("give", "minecraft:raw_gold_block", 32, "Gold Ore Tithe"),
    ("give", "minecraft:redstone_lamp", 64, "Lamp Tithe"),
    ("give", "minecraft:tinted_glass", 64, "Tinted Tithe"),
    ("give", "minecraft:quartz", 512, "Quartz Tithe"),
    ("give", "minecraft:amethyst_block", 64, "Crystal Tithe"),
    ("give", "minecraft:calcite", 256, "Calcite Tithe"),
    ("give", "minecraft:diamond_horse_armor", 2, "Royal Barding"),
    ("give", "minecraft:netherite_scrap", 32, "Debris Tithe"),
    ("give", "minecraft:cobblestone", 1024, "Stone Mountain"),
    ("give", "minecraft:oak_log", 512, "Forest Clearer"),
    ("give", "minecraft:hay_block", 128, "Grain Silo"),
    ("give", "minecraft:carrot", 512, "Carrot Empire"),
    ("give", "minecraft:potato", 512, "Potato Empire"),
    ("give", "minecraft:sugar_cane", 512, "Sugar Plantation"),
    ("give", "minecraft:pumpkin", 128, "Pumpkin Kingdom"),
    ("give", "minecraft:melon", 128, "Melon Kingdom"),
    ("give", "minecraft:cooked_chicken", 256, "Feast Hall"),
    ("give", "minecraft:bread", 256, "Royal Bakery"),
    ("give", "minecraft:glass", 512, "Glass Palace"),
    ("give", "minecraft:bricks", 512, "Brick Citadel"),
    ("give", "minecraft:quartz_block", 256, "Marble Halls"),
    ("give", "minecraft:sea_lantern", 64, "Lighthouse"),
    ("give", "minecraft:prismarine", 256, "Atlantis"),
    ("give", "minecraft:blackstone", 512, "Obsidian Keep"),
    ("give", "minecraft:deepslate_bricks", 512, "Deep Halls"),
    ("give", "minecraft:white_wool", 256, "Royal Tapestry"),
    ("give", "minecraft:bookshelf", 64, "Grand Library"),
    ("give", "minecraft:experience_bottle", 64, "Bottled Legends"),
    ("give", "minecraft:golden_apple", 32, "Golden Orchard"),
    ("give", "minecraft:glistering_melon_slice", 64, "Glittering Pantry"),
    ("give", "minecraft:ghast_tear", 16, "Ghastly Collection"),
    ("give", "minecraft:blaze_rod", 128, "Blaze Arsenal"),
    ("give", "minecraft:breeze_rod", 128, "Breeze Arsenal"),
    ("give", "minecraft:phantom_membrane", 64, "Phantom Silk"),
    ("give", "minecraft:rabbit_foot", 16, "Lucky Charms"),
    ("give", "minecraft:nautilus_shell", 16, "Nautilus Vault"),
    ("give", "minecraft:turtle_scute", 32, "Turtle Sanctuary"),
    ("give", "minecraft:armadillo_scute", 32, "Armadillo Vault"),
    ("stat", "minecraft:walk_one_cm", 5000000, "Fifty Kilometres"),
    ("stat", "minecraft:sprint_one_cm", 5000000, "Fifty Kilometre Sprint"),
    ("stat", "minecraft:boat_one_cm", 2000000, "Circumnavigator"),
    ("stat", "minecraft:horse_one_cm", 2000000, "Rider of the Realm"),
    ("stat", "minecraft:swim_one_cm", 1000000, "Ocean Swimmer"),
    ("stat", "minecraft:fish_caught", 500, "Ocean's Bounty"),
    ("stat", "minecraft:animals_bred", 500, "Ark Builder"),
    ("stat", "minecraft:traded_with_villager", 250, "Merchant Prince"),
    ("stat", "minecraft:enchant_item", 300, "Grand Enchanter"),
    ("stat", "minecraft:interact_with_brewingstand", 300, "Grand Alchemist"),
    ("stat", "minecraft:raid_win", 10, "Raid Conqueror"),
    ("stat", "minecraft:mob_kills", 10000, "Ten Thousand Fallen"),
    ("stat", "minecraft:jump", 25000, "Ten Thousand Leaps"),
    ("stat", "minecraft:play_time", 1728000, "A Full Day"),
    ("stat", "minecraft:play_time", 8640000, "Five Days in the Realm"),
    ("kill", "minecraft:wither", 5, "Wither's Bane"),
    ("kill", "minecraft:ender_dragon", 5, "Dragon Hunter"),
    ("have", "minecraft:end_crystal", 16, "Crystal Crown"),
    ("craft", "minecraft:lodestone", 4, "Waystones"),
    ("give", "minecraft:diamond_block", 16, "Diamond Treasury"),
    ("give", "minecraft:oxidized_copper", 64, "Verdigris Vault"),
    ("give", "minecraft:raw_copper_block", 64, "Copper Ore Vault"),
    ("give", "minecraft:iron_block", 128, "Iron Treasury"),
    ("give", "minecraft:nether_star", 3, "Starfall"),
    ("craft", "minecraft:beacon", 5, "The Eternal Light"),
    ("xp", "", 75, "Seventy-Five Levels"),
    ("xp", "", 100, "Hundred Levels"),
    ("give", "minecraft:netherite_block", 2, "Throne of Netherite"),
    ("have", "minecraft:enchanted_golden_apple", 5, "Legend of the Ledger"),
])
